### ISSUE TITLE
Update bazelbuild/rules_kotlin to latest from hsyed/rules_kotlin

### ISSUE THREAD

**Issue by davidstanke** [bazelbuild/rules_kotlin#1]
Hey Hassan! The repo is ready. Can you replay any commits from the last few days here? Then update the readme in hysed/rules_kotlin to direct people to here as the new SoT.

**Comment by hsyed** [comment]
Hey Dave, Done !

The GitHub pages needs to be activated and it should just work.

**Comment by davidstanke** [comment]
Pages are active. FYI, it wasn't working until I stripped the whitespace and skydoc comment... but that may have just been what was necessary to trigger it to publish.
