### ISSUE TITLE
Anyone who migrated a large Kotlin repo from Gradle to Bazel?

### ISSUE THREAD

**Issue by elshad-faire** [bazelbuild/rules_kotlin#1002]
Hello everyone. Sorry if this is not the right way to ask this sort of question. I could not find a contact in the github page for this project.

We have a relatively large Kotlin repo that is using Gradle. I have been trying to see how Bazel would work for us. But making the decision to switch to Bazel is a large commitment.

Are there any teams that are using Bazel for a large Kotlin repo that we can talk to? It would be great to talk any team who migrated their large Kotlin repo from Gradle to Bazel. We are essentially trying to understand if there are any unexpected benefits or issues long term.

Thanks!

**Comment by Bencodes** [comment]
@elshad-faire We have a mostly-Kotlin codebase and use Bazel. Happy to chat if you reach out on the Bazel slack community.

**Comment by elshad-faire** [comment]
I will close this issue as now I know where to search thanks to @Bencodes :)
