### ISSUE TITLE
retrieve generated class/src jars from rules_kotlin `KtJvmInfo`

### ISSUE THREAD

**Issue by xuansontrinh** [bazelbuild/rules_kotlin#1032]
Hi gurus,
I am working on supporting Bazel plugin in IntelliJ IDEA and currently, we are having issues caused by the behaviours of generated class/src jars from `rules_kotlin`'s `KtJvmInfo`. Here are the 2 issues that I would like to ask for your help:

**Issue 1**: 
I have an annotation processor that targets a specific annotation `A`, I register this processor using `java_plugin` rule and build the target using `kt_jvm_library`.

What I expect: The generated class jar file should contain only classes annotated with `A`.
What I get: There are a lot of non-annotated classes bundled inside my generated class jar.

I attempted to convert one of the affected classes to Kotlin code, and the class disappeared from the bundle when rebuilding.
Is this the expected behaviour with Java annotation processing? And if possible, how can I unbundle the affected classes?

Here is the code that you can use to reproduce the issue: 
[test-generated.zip](https://github.com/bazelbuild/rules_kotlin/files/12658461/test-generated.zip)
(before using, please help me update the `rules_kotlin` in the workspace back to the release of `rules_kotlin`, earlier I changed it to point to a local repo for debugging).
after building this example, you can try creating an aspect to retrieve info from `KtJvmInfo` provider of target `//base`. The `provider.annotation_processing.class_jar` will point to `bazel-bin/base/base-java.jar`, which contains all 3 classes: `A`, `B`, and `AGenerated`.
In this example, `B` is not an annotated class, and also I don't expect `A` to be included as this is for "generated class".

**Issue 2**:
I believe it is not enough to just accumulate 2 jars, one for class jar and one for src jar in annotation processing as there are more to that. From the source code of `rules_kotlin`, I see that we can also accumulate kapt generated srcs and more. How can we reliably get all of that? In short, we would need all the generated src/class jars possible.

**Comment by restingbull** [comment]
Are you using the [ijwb aspect](https://github.com/bazelbuild/intellij/blob/18184c234a04ef543e7ce26f0177611e73c0d0e2/aspect/intellij_info_impl.bzl#L997-L1008) or something else?

**Comment by jastice** [comment]
It would be the [bazel-bsp aspect](https://github.com/JetBrains/bazel-bsp/blob/master/aspects/rules/kt/kt_info.bzl)

**Comment by xuansontrinh** [comment]
@restingbull here is the exact place that we accumulate generated jars in case you need it for debugging: https://github.com/JetBrains/bazel-bsp/blob/119eb05577f1235e5491880ff864f8ea4ce35f3a/aspects/rules/jvm/jvm_info.bzl#L49

**Comment by restingbull** [comment]
The rules export `JavaInfo` in addition to `KtJvmInfo` (for `rules_java` interopt)

You should be able to find most of what you need from that. Lmk if there is something missing.

**Comment by restingbull** [comment]
That said, is there a doc on how to setup Intellij to use this bazel integration?

**Comment by xuansontrinh** [comment]
> The rules export `JavaInfo` in addition to `KtJvmInfo` (for `rules_java` interopt)
> 
> You should be able to find most of what you need from that. Lmk if there is something missing.

@restingbull correct me if I am wrong but the `JavaInfo` that the rules support does not have info about `annotation_processing` jars ([link](https://github.com/bazelbuild/rules_kotlin/blob/67505f3c006073a546c14066a733fdfd2f5ccff2/kotlin/internal/jvm/compile.bzl#L594-L603)) so I don't know what is the additional info that I can expect to get from that provider.

The provider `KtJvmInfo` seems to have an `annotation_processing` field but it only gives me a pair of class + source jars, which have issues as I mentioned in the issue.

My need is to be able to retrieve the src/class jars that solely contain (all) the generated classes. I can contribute if needed, as long as I know that it is possible to pull this off.

**Comment by xuansontrinh** [comment]
> That said, is there a doc on how to setup Intellij to use this bazel integration?

you can clone [this plugin](https://github.com/JetBrains/intellij-bsp) and import/run it using IntelliJ IDEA. If you prefer to build the plugin yourself and add manually to IntelliJ IDEA, you can use the command `./gradlew buildPlugin` and refer to `build/distributions` for the plugin. You can use this plugin to open the test project that I included in the issue description.

If you want to change something to the aspects for testing purposes, please refer to `.bazelbsp/aspects` inside your project. e.g. the place where you can find the aspect for getting generated jars is `.bazelbsp/aspects/rules/jvm/jvm_info.bzl`. After changing things, please clean the project with `bazel clean` and reload the project using the reload button in the plugin toolwindow (it is called `BSP`).
