### ISSUE TITLE
KotlinKapt fails on Java 21 with java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by cheister** [bazelbuild/rules_kotlin#1062]
When running with Java 21 the KotlinKapt action fails with
```
exception: java.lang.IllegalAccessError: superclass access check failed: class org.jetbrains.kotlin.kapt3.base.javac.KaptJavaCompiler (in unnamed module @0x229fa008) cannot access class com.sun.tools.javac.main.JavaCompiler (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.main to unnamed module @0x229fa008
```

For now, the workaround is to add the following to the `.bazelrc` file
```
build --worker_extra_flag='KotlinKapt=--wrapper_script_flag=--jvm_flags=--add-opens=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED'
```

but would be nice to add this flag to the jvm_opts for KotlinKapt

**Comment by manuelddahmen** [comment]
I have the same problem since this morning with Java 21, Gradle 8.7 and Kotlin 1.9.20
I searched for solutions and try to fix this issue on my computer.
Do you have a solution for Android Studio on Windows 11?
