### ISSUE TITLE
Release notes for v1.9.0 contain incorrect url for http_archive

### ISSUE THREAD

**Issue by srabraham** [bazelbuild/rules_kotlin#1065]
The release notes for release v1.9.0 contain this snippet

```python
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_kotlin",
    sha256 = "5766f1e599acf551aa56f49dab9ab9108269b03c557496c54acaf41f98e2b8d6",
    strip_prefix = "rules_kotlin-1.9.0",
    url = "https://github.com/buildfoundation/rules_kotlin/releases/download/v1.9.0/rules_kotlin-v1.9.0.tar.gz",
)
```

but when I actually click on the above link or use it in a rule, I get a 404: https://github.com/buildfoundation/rules_kotlin/releases/download/v1.9.0/rules_kotlin-v1.9.0.tar.gz

is it supposed to reference the repo bazelbuild/rules_kotlin instead? This does work for me: https://github.com/bazelbuild/rules_kotlin/releases/download/v1.9.0/rules_kotlin-v1.9.0.tar.gz

**Comment by Bencodes** [comment]
Thanks for catching this.

I updated the description to point at the correct URL.

**Comment by srabraham** [comment]
> Thanks for catching this.
> 
> I updated the description to point at the correct URL.

Thank you!

**Comment by th0masb** [comment]
> Thanks for catching this.
> 
> I updated the description to point at the correct URL.

The release notes are still wrong. The archive at the updated download link has no "rules_kotlin-1.9.0" prefix to strip so bazel complains.

**Comment by Bencodes** [comment]
> The release notes are still wrong.

Argh thanks for pointing that out. The release notes have been updated again and have a PR up for the strip_prefix changes here https://github.com/bazelbuild/rules_kotlin/pull/1070.

> Why have we switched the repository name from "io_bazel_rules_kotlin" to "rules_kotlin"?

So that we are more in line with what other rules are doing and so that the rules name now matches the Github repository. Ex: https://github.com/bazelbuild/rules_android/commit/ad1727aae8f5183b6d4baa9802bad530d8c366db
