### ISSUE TITLE
non-persistent worker race condition: missing external kotlin-compiler.jar

### ISSUE THREAD

**Issue by zsiegel** [bazelbuild/rules_kotlin#107]
I seem to have gotten into a strange state that I am unable to find any resolution for.

When running `bazel build //...` I end up with the following missing kotlin compiler issue.

```
ERROR: /Users/zsiegel/src/github.com/my-app-folder/BUILD:45:1: Compiling Kotlin //:config { kt: 1, java: 0, srcjars: 0 } failed (Exit 1)
Exception in thread "main" java.lang.IllegalStateException: file did not exist: external/com_github_jetbrains_kotlin/lib/kotlin-compiler.jar
	at io.bazel.kotlin.builder.utils.IOUtils.verified(IOUtils.kt:74)
	at io.bazel.kotlin.builder.utils.IOUtils.resolveVerified(IOUtils.kt:69)
	at io.bazel.kotlin.builder.toolchain.KotlinToolchain$Companion.createClassLoader(KotlinToolchain.kt:52)
	at io.bazel.kotlin.builder.toolchain.KotlinToolchain$Companion.createToolchain(KotlinToolchain.kt:75)
	at io.bazel.kotlin.builder.toolchain.KotlinToolchain.createToolchain(KotlinToolchain.kt)
	at io.bazel.kotlin.builder.KotlinBuilderMain.main(KotlinBuilderMain.java:26)
```

This exact build seems to work on another machine but I am unable to track down why this issue is occurring on some machines. I have tried digging through the verbose outputs but I have no idea why this file might be missing. 

Any ideas or thoughts on how to debug and resolve this?

Thanks

**Comment by zsiegel** [comment]
Small update.

If I look into `ls -al $(bazel info output_base)/external/com_github_jetbrains_kotlin/lib/` I do in fact see the `kotlin-compiler.jar` file.

**Comment by hsyed** [comment]
@zsiegel interesting, what version of bazel, OS, kotlin rules comit hash, and kotlin compiler version are you using ? does a `bazel clean --expunge` fix the problem ?

**Comment by zsiegel** [comment]
Tried the `bazel clean --expunge` a few times and got nowhere. 

Details are below...

```
Build label: 0.15.2-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jul 17 13:06:19 2018 (1531832779)
Build timestamp: 1531832779
Build timestamp as int: 1531832779
```

```
kotlin_release_version="1.2.60"
rules_kotlin_version = "d97fc6a14f553b125636700da1c8883229913922"

http_archive(
    name = "io_bazel_rules_kotlin",
    urls = ["https://github.com/bazelbuild/rules_kotlin/archive/%s.zip" % rules_kotlin_version],
    type = "zip",
    strip_prefix = "rules_kotlin-%s" % rules_kotlin_version
)

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")
kotlin_repositories(kotlin_release_version=kotlin_release_version)
kt_register_toolchains()
```

**Comment by zsiegel** [comment]
Im on High Sierra 10.3.6

**Comment by hsyed** [comment]
ok cool so we are on the same OS, that makes it a bit easier to get to the bottom of the issue. The rules repo has the dagger coffee app project in it and tests. Can you check out the repo and load it into intellij and run the tests / the app (hopefully the problem will persist) ?

**Comment by zsiegel** [comment]
No luck with intellij so far but I can build and run the sample app from the command line like so.

`bazel build //examples/dagger:coffee_app`

```
bazel build //examples/dagger:coffee_app
Starting local Bazel server and connecting to it...
...........
INFO: SHA256 (https://github.com/bazelbuild/rules_nodejs/archive/df3d2f577ec57ef5a622c809288a29545470c15d.zip) = a0a93cd649d3c90c06c32a5b8ac1f5fe439dcfa40e790d30429d209c8b8d2af4
INFO: SHA256 (https://github.com/bazelbuild/rules_sass/archive/38989d69ef3ba5847640f007fee5cc489be6ede9.zip) = 6df094611bb26d6dfa53f5227ec253e1a64bdc75fc0aa0b0677de58e682c529d
INFO: SHA256 (https://github.com/bazelbuild/skydoc/archive/f531844d137c7accc44d841c08a2a2a366688571.zip) = 071536265b1d99c1eea3bd59df8f0c28e806b00c8e8e3ca8e2d82ede96a561bc
INFO: SHA256 (https://github.com/bazelbuild/bazel-skylib/archive/6301f974f02350fe973d8631cf1bb87ab8d2a2bd.zip) = 94c07aa916b09f1f13d405cc859eda431b8f8901489b2b34d5b7079b1c2d2da2
DEBUG: /private/var/tmp/_bazel_zsiegel/07f4dbd95a2243240a68d96cb2eaa594/external/bazel_tools/tools/build_defs/repo/http.bzl:43:9: ctx.attr.build_file @io_bazel_rules_kotlin//kotlin:BUILD.com_github_jetbrains_kotlin, path /private/var/tmp/_bazel_zsiegel/07f4dbd95a2243240a68d96cb2eaa594/external/io_bazel_rules_kotlin/kotlin/BUILD.com_github_jetbrains_kotlin
INFO: Analysed target //examples/dagger:coffee_app (67 packages loaded).
INFO: Found 1 target...
Target //examples/dagger:coffee_app up-to-date:
  bazel-bin/examples/dagger/coffee_app.jar
  bazel-bin/examples/dagger/coffee_app
INFO: Elapsed time: 25.549s, Critical Path: 15.83s
INFO: 14 processes: 10 darwin-sandbox, 4 worker.
INFO: Build completed successfully, 25 total actions
```

**Comment by hsyed** [comment]
Missing coroutine dep is alarming, it might be an indicator of some other problems with the fs abstractions in bazel  (the local caching layer ? ). 

you can ignore the file hashing tests. I need to get to the bottom of all the reasons of why hashes on the files change. 

```bazel test //all_tests``` excludes the local tests.

**Comment by zsiegel** [comment]
Great call. Persistent worker was the problem. I had it enabled on my other machine but checked my .bazelrc on this machine and it was nowhere to be found.

**Comment by hsyed** [comment]
@zsiegel I'll try and replicate the problem and then fix the regression.

The Kotlin rules have to be run as persistent workers soon since some of the new developments I am working on would break a build up into stages and without persistent workers the build would take a lifetime. I need to find out how to make make the persistent workers the default.

**Comment by hsyed** [comment]
@plumpy thanks, I can replicate the issue as well in another repository. 

I'm waiting on feedback on [this issue] (https://github.com/bazelbuild/bazel/issues/5805) before I put a fix in. In the mean time I recommend setting a persistent worker.

**Comment by hsyed** [comment]
fixed
