### ISSUE TITLE
JS Support

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/rules_kotlin#108]
I have javascript compilation working, and support in the builder for it. Libs can depend on other local libs. But currently that is it (can't depend on node modules I think).

I am not a JS developer so I don't know what would and wouldn't be idiomatic. I need a JS developer as a client. I need a real world example app using JS modules, rules_nodes and local local Kotlin libraries being used in concert in the example directory.  

@thewoolleyman do you want to be this guy ? I can push the existing work after tidying it up in a separate branch.

**Comment by thewoolleyman** [comment]
@hsyed Yes, If you have something working, even minimal, I'd love to try it out.  

I'm wanting to use it on a greenfield project, so my requirements should be minimal, and I want to be as flexible and bazel-idiomatic as I can (I mainly just REALLY don't want to use gradle or maven, which are the only other real choices for multiplatform kotlin projects).  I can open issues (and fix if I can) for anything that doesn't work or I don't understand.  So, seems like a great fit.

Thanks!
-- Chad

**Comment by hsyed** [comment]
@thewoolleyman basic js support is available. It's not in master yet.

**Comment by thewoolleyman** [comment]
@hsyed Thanks! I'll start playing with it when I have time, and use this issue to report any problems I can't get past.

**Comment by thewoolleyman** [comment]
I'm getting the following error when trying to build or fetch any of the node examples:

```
$ bazel fetch //examples/node/express:acme-routes
ERROR: error loading package 'examples/node/express': Extension file not found. Unable to load package for '@build_bazel_rules_nodejs//:defs.bzl': The repository could not be resolved
Building: no action
```

I'm probably missing something basic due to unfamiliarity with bazel, but I don't know what.

Thanks...

**Comment by hsyed** [comment]
Are you running the commands from the `examples/node` directory ? it is a nested workspace. If you run the commands from the root you will be in the root workspace.

**Comment by thewoolleyman** [comment]
Ah ok, it works from the `examples/node` directory.

I was confused because `bazel build //examples/dagger:dagger_lib` works fine from the root; I expected this to be the same.

**Comment by thewoolleyman** [comment]
@hsyed  The example works fine for me (if run from the correct directory).  I can build it and run the express app successfully.

I will try using it in a separate app when I get time.

My only suggestion is to add `examples/node/node_modules` to the `.gitignore` file.

**Comment by hsyed** [comment]
node_modules should not be in the workspace. The example relies on rules nodejs to manage the node dependencies.

**Comment by cgruber** [comment]
JS support exists at this point, but isn't well-maintained. I'm going to close this, as it is technically present, but we could use help from folks who have an interest in this capability.

There's also a larger kotlin multiplatform effort we are starting to think about, and this may be subsumed in that.
