### ISSUE TITLE
WorkerEnvironmentTest is failing at Bazel@HEAD

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_kotlin#1091]
[https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3523#018c6104-a6cf-4ce1-838f-df358c3ec183](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3523#018c6104-a6cf-4ce1-838f-df358c3ec183)

Platform :  [rules\_kotlin (Tests without Bzlmod (Ubuntu 18.04)](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3523#018c6104-a6cb-4766-b346-9bb4d5adb673)

Logs:

```

//src/test/kotlin/io/bazel/worker:WorkerEnvironmentTest                  FAILED in 3 out of 3 in 0.6
```

steps:

```

git clone -v https://github.com/bazelbuild/rules_kotlin.git
git reset e06ba90928b93bd6075ca7d72de49a6f23602f51 --hard
export USE_BAZEL_VERSION=68c6ddafd7535b710fa5e978ba4f8d06b91d922c
bazel test --enable_bzlmod=false //:all_tests
```

CC Greenteam @comius

**Comment by Bencodes** [comment]
I believe this is a flake that should pass on a retry.

**Comment by sgowroji** [comment]
CI retry solved it. Thanks for the update.
