### ISSUE TITLE
kotlin compiler and ksp repositories fail to initialize on windows

### ISSUE THREAD

**Issue by ydynnikov** [bazelbuild/rules_kotlin#1097]
Reproducible both on our repo with bazel 7.0.0 (using bzlmod) and when I do fresh checkout of this repository on tag v1.9.0

Platform: Windows 11

`bazel build //...` fails with errors looking like 
```
ERROR: C:/users/user/_bazel_user/7vi7p7qd/external/rules_kotlin~1.9.0/kotlin/compiler/BUILD.bazel:23:17: no such target '@@rules_kotlin~1.9.0~rules_kotlin_extensions~com_github_google_ksp//:symbol-processing-cmdline.jar': target 'symbol-processing-cmdline.jar' not declared in package '' defined by C:/users/user/_bazel_user/7vi7p7qd/external/rules_kotlin~1.9.0~rules_kotlin_extensions~com_github_google_ksp/BUILD.bazel (Tip: use `query "@@rules_kotlin~1.9.0~rules_kotlin_extensions~com_github_google_ksp//:*"` to see all the targets in that package) and referenced by '@@rules_kotlin~1.9.0//kotlin/compiler:symbol-processing-cmdline'
```

What I've found by log-debugging (I don't know how to debug starlark in any other way yet :-( ): 
* If you put logs before `kotlin_compiler_repository`  in `intialize.release.bzl`, it prints
* If you put logs in `_kotlin_compiler_impl` in `compiler.bzl`, it prints 
* If you put logs in `_ksp_compiler_plugin_repository_impl` in `ksp.bzl`, it doesn't print 
* If you explicitly specify all the jars listed in `_JARS_INSIDE_REPO` (in `ksp.bzl` ) in srcs of filegroup in `BUILD.com_github_google_ksp.bazel`, it works and downloads all jars. After that you can replace it back with `glob` and it will still work as jars are already there. 
  * But there comes another problem with android sdk:  
  ```
  ERROR: C:/users/user/_bazel_user/alsd73yo/external/bazel_tools/tools/android/BUILD:14:27: in :android_sdk attribute of android_tools_defaults_jar rule @bazel_tools//tools/android:android_jar: alias '@bazel_tools//tools/android:sdk' referring to filegroup rule '@androidsdk//:sdk' through '//external:android/sdk' is misplaced here (expected android_sdk)
  ```
  
  
  I don't see any tests for bzlmod on windows among other builds in buildkite, is it even supported now? 

  https://buildkite.com/bazel/rules-kotlin-kotlin/builds/3877#018cb2e4-35d7-473e-8c59-08ff4f6e5405

**Comment by restingbull** [comment]
This is for bzlmod, correct?

**Comment by ydynnikov** [comment]
@restingbull hi, yes, it's for bzlmod. I've already dug deeper and found that it was due to the fact that when you use terminal in IDEA, it's powershell by default. When launching bazel from msys shell there is no problem

Worth noting that the problem could be visible earlier: `repository_ctx.execute` returns status struct that could be checked for failures. In my case failure was something like "CreateProcessW(...): mv is not recognized as a program"

**Comment by ydynnikov** [comment]
@restingbull hi, I've managed to get this working both in msys2 and in powershell 

For powershell you need `mv.exe` to be exposed to powershell, so putting msys's `/usr/bin`  to PATH worked 

There is another problem with running tests, but it deserves its own ticket
