### ISSUE TITLE
WorkerEnvironmentTest is failing with Bazel@HEAD

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_kotlin#1098]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3566#018ccd5b-886a-4ce1-8d19-e3409778a675

Platform :  [rules\_kotlin (Tests without Bzlmod (Ubuntu 18.04)](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3566#018ccd5b-886a-4ce1-8d19-e3409778a675)

Logs:

```

//src/test/kotlin/io/bazel/worker:WorkerEnvironmentTest                  FAILED 
```

Steps:

```

git clone -v https://github.com/bazelbuild/rules_kotlin.git 
git reset 18142b7b48dc6e42c55de04a5301b555ab43f269 --hard
export USE_BAZEL_VERSION=955b0896819ba7608d13fa6a33ba0ba9d8473004
bazel test --enable_bzlmod=false //:all_tests
```

CC Greenteam @mai93

**Comment by mai93** [comment]
passed after retry
