### ISSUE TITLE
[Bazel CI] Test logs failed for kotlin-builder at Bazel@HEAD in CI


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_kotlin#1129]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3711#018e2bad-e46a-411e-9bc7-800fb1641710

Platform: Ubuntu

Logs:

```
//src/test/kotlin/io/bazel/kotlin:KotlinJvm13Test
//src/test/kotlin/io/bazel/kotlin:KotlinJvmAssociatesBasicVisibilityTest
//src/test/kotlin/io/bazel/kotlin:KotlinJvmBasicAssertionTest      
//src/test/kotlin/io/bazel/kotlin:KotlinJvmKaptAssertionTest 
...
```

Culprit:

Steps:

```
 git clone https://github.com/bazelbuild/rules_kotlin
git reset e5283665675c94e539d1aa00e9582928d3b25a2e  --hard
export USE_BAZEL_VERSION=3697397569e25a29a828fb46b26302876d372e26
bazel test //:all_tests 
```

CC Greenteam @Wyverald

**Comment by Wyverald** [comment]
This seems to be due to the JDK updates on CI machines. @meteorcloudy do we need to do anything here?

**Comment by meteorcloudy** [comment]
@Bencodes This probably need a similar fix in https://github.com/bazelbuild/rules_kotlin/blob/b9380cd1ce3a2c7ae337531c455c425fac38302c/src/test/kotlin/io/bazel/kotlin/defs.bzl#L26 as https://github.com/bazelbuild/bazel/commit/6783339e3fd21655b7fa3be2daedde4491ae0348 to add `-Djava.security.manager=allow` for the Java test runner.

**Comment by sgowroji** [comment]
CI is passing now and shows Green. We can close this issue.
