### ISSUE TITLE
Failed tests are reported as successful

### ISSUE THREAD

**Issue by zalewskise** [bazelbuild/rules_kotlin#1141]
I was looking into writing some tests and to my surprise, tests that supposed to be failing were reported as successful on my machine. Tried out breaking tests on CI in https://github.com/bazelbuild/rules_kotlin/pull/1140 and it's green.

Broken since: https://github.com/bazelbuild/rules_kotlin/pull/1128

**Comment by zalewskise** [comment]
cc: @restingbull

**Comment by restingbull** [comment]
Fixed in https://github.com/bazelbuild/rules_kotlin/pull/1142
