### ISSUE TITLE
Support Kotlin 2.0

### ISSUE THREAD

**Issue by jbarr21** [bazelbuild/rules_kotlin#1156]
Kotlin 2.0 Beta releases are now available ([link](https://github.com/JetBrains/kotlin/releases/tag/v2.0.0-Beta5)). Currently if I try to register a custom toolchain with the language level set to 2.0 the build fails with the following message:

```
ERROR: package contains errors: : //:kotlin_toolchain_impl: invalid value in 'language_version' attribute: has to be one of '1.1', '1.2', '1.3', '1.4', '1.5', '1.6', '1.7', '1.8' or '1.9' instead of '2.0'
```

**Comment by Bencodes** [comment]
Are you using an older version of `rules_kotlin` right now? The 2.0 versions got added a while back in anticipation of the 2.x releases but they have not been tested yet. https://github.com/bazelbuild/rules_kotlin/pull/1086
