### ISSUE TITLE
[Bazel CI] WorkerEnvironmentTest is failing at Bazel@HEAD


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_kotlin#1163]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3815#018f1895-3a6a-4333-9900-8a01fa7448eb

rules_kotlin : https://buildkite.com/bazel/rules-kotlin-kotlin/builds/4164#018f17b8-20b5-42fb-9902-610c39f73654

 Platform: MacOS

 Logs: 
```

FAILED: [0m//src/test/kotlin/io/bazel/worker:WorkerEnvironmentTest 
``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/rules_kotlin
git reset cb82644daed72d783ab410a635316638596a00b8  --hard
export USE_BAZEL_VERSION=3beaaaf23e4f6e9071ef7eabced7d64513573e80
bazel test //:all_tests 
 ``` 
 CC Greenteam @wyverald

**Comment by sgowroji** [comment]
CC @Bencodes

**Comment by restingbull** [comment]
Will remove the flaky test.

**Comment by sgowroji** [comment]
CI is green now. We can close this issue now.
