### ISSUE TITLE
Add android e2e test once native rules support it.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/rules_kotlin#120]
Once [the native android rules](https://github.com/bazelbuild/rules_kotlin) have support for android remote android toolchains wire up an android example (#119) as an e2e test. 

@jin added you to this issue as well -- I'll take care of this one once the native rules support non-local toolchains.

Beyond compiling and launching the example I don't think we need to test anything else since the integration is just a simple sandwich macro for now WDYT ? .

**Comment by cgruber** [comment]
The android example kind of is that. We can build a better one, but for now, we ARE testing the rules in CI on android projects.
