### ISSUE TITLE
Non-Compiling KSP code should not be deleted

### ISSUE THREAD

**Issue by TwoClocks** [bazelbuild/rules_kotlin#1249]
It's pretty much impossible to debug KSP code that generates code with a compilation error.

bazel spits out the error, but references a file name in a directory in `/tmp` that is deleted before bazel exits.

the gensrc.jar file isn't generated in bazel-bin.

Effectively the code that doesn't compile no longer exists, and can't be seen.

So the only way to debug is to roll back all your changes until the last time it worked, then add then back in again one at a time... massive PIA. Or start randomly commenting out your KSP code until it works... Or some other stone-age form of feeling around in the dark.

Please don't delete the non-compiling code.

**Comment by restingbull** [comment]
I believe you are looking for [--sandbox_debug](https://bazel.build/versions/8.0.0/reference/command-line-reference#flag--sandbox_debug) flag. If an action fails, the end artifacts are not available to bazel (as it is not correct.), and therefore wouldn't show up in bazel-bin or genfiles.

e.g. the rules do not control the deletion of intermediate artifacts. Feel free to file a bug with bazel.

**Comment by TwoClocks** [comment]
Yep. That's what I was looking for.

Thanks!
