### ISSUE TITLE
Unable to build basic Android project with kt_android_library

### ISSUE THREAD

**Issue by Pmcneice** [bazelbuild/rules_kotlin#133]
I've been trying to create an example Android project - more for my own reference than anything else - here: https://github.com/Pmcneice/AndroidBazelExample 

It's a simple project - basically the default Android Studio project template - that contains a single `.java` activity and a single `.kt` activity. I hope to include KAPT and databinding examples in that project moving forward.

If I remove the Kotlin activity i can compile the project with this `android_binary` rule:

```
android_binary(
    name = "AndroidBazelExample",
    custom_package = PACKAGE,
    manifest = MANIFEST,
    srcs = glob(["src/main/java/**"]),
    resource_files = glob(["src/main/res/**"]),
    multidex = "native",
    dex_shards = 10,
    deps = [
        gmaven_artifact("androidx.appcompat:appcompat:aar:1.0.0-beta01"),
        gmaven_artifact("androidx.constraintlayout:constraintlayout:aar:1.1.2")
    ]
)
```

However, trying to compile with the following rules does not:

```
android_binary(
    name = "AndroidBazelExample",
    custom_package = PACKAGE,
    manifest = MANIFEST,
    multidex = "native",
    dex_shards = 10,
    deps = [
        "src"
    ]
)

kt_android_library(
    name = "src",
    custom_package = PACKAGE,
    manifest = MANIFEST,
    srcs = glob(["src/main/java/**"]),
    resource_files = glob(["src/main/res/**"]),
    deps = [
        gmaven_artifact("androidx.appcompat:appcompat:aar:1.0.0-beta01"),
        gmaven_artifact("androidx.constraintlayout:constraintlayout:aar:1.1.2")
    ]
)
```

Building with those rules always gives me an error about resources not found in the `appcompat` library. For example:

```
Error at 16 : /tmp/resource_validator_tmp2551691630083267333/tmp-expanded/res/values/values.xml:16: error: Error: No resource found that matches the given name: attr 'colorPrimaryDark'.
```

I've tried explicitly including the library dependencies and resources files in the `android_library` block just in case the dependencies of the `kt_android_library` block weren't being included but that gives me the same error.

Any ideas? I know there's some comments from @jin in https://github.com/bazelbuild/rules_kotlin/issues/119 about some potential dependency issues but I wasn't sure if this was related or not?

**Comment by jin** [comment]
Yes, that’s the same issue.

**Comment by hsyed** [comment]
Cool, ill have a look tommorow or monday.

**Comment by hsyed** [comment]
I'm using the example app above to fix the rules. Threading the deps attr into the `native.android_library` before passing it to the kotlin library is the fix I guess. 

```
app/src/main/java/uk/co/mcneice/bazeltest/MainActivity.java:10: error: cannot access TaskStackBuilder
public class MainActivity extends AppCompatActivity {
       ^
  class file for androidx.core.app.TaskStackBuilder not found
1 error
error: supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class androidx.appcompat.app.AppCompatActivity, unresolved supertypes: androidx.fragment.app.FragmentActivity, androidx.core.app.TaskStackBuilder.SupportParentable
    class androidx.appcompat.app.ActionBarDrawerToggle, unresolved supertypes: androidx.drawerlayout.widget.DrawerLayout.DrawerListener
```

I'm getting this now. Where do I find these dependencies ?

**Comment by hsyed** [comment]
@jin the package docs should contain the maven coordinates of the artefacts. It's quite hard to find what the coords for `android.core.app` might be from [here]( https://developer.android.com/reference/androidx/core/app/package-summary)

**Comment by hsyed** [comment]
I've put a fix in for this. Please check and close.

**Comment by Pmcneice** [comment]
Did you manage to solve the dependency errors you mentioned above? I've got the same thing.

I would have thought that those core dependencies would have been pulled in as part of this:

`gmaven_artifact("androidx.appcompat:appcompat:aar:1.0.0-beta01")`

which in turn expands to:

```
  aar_import_external(
      name = 'androidx_appcompat_appcompat_1_0_0_beta01',
      licenses = ['notice'], # apache
      aar_urls = ['https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat/1.0.0-beta01/appcompat-1.0.0-beta01.aar'],
      aar_sha256 = '',
      deps = [
        '@androidx_collection_collection_1_0_0_beta01//jar',
        '@androidx_cursoradapter_cursoradapter_1_0_0_beta01//aar',
        '@androidx_fragment_fragment_1_0_0_beta01//aar',
        '@androidx_core_core_1_0_0_beta01//aar',
        '@androidx_vectordrawable_vectordrawable_1_0_0_beta01//aar',
        '@androidx_vectordrawable_vectordrawable_animated_1_0_0_beta01//aar',
        '@androidx_legacy_legacy_support_core_utils_1_0_0_beta01//aar',
        '@androidx_annotation_annotation_1_0_0_beta01//jar',
      ],
    )
```

It's worth mentioning that I don't need to add any extra dependencies to build that app if i get rid of the Kotlin file.

**Comment by hsyed** [comment]
I used this [index](https://dl.google.com/dl/android/maven2/index.html), to discover the following:

```
        gmaven_artifact("androidx.appcompat:appcompat:aar:1.0.0-beta01"),
        gmaven_artifact("androidx.annotation:annotation:1.0.0-beta01"),
        gmaven_artifact("androidx.fragment:fragment:aar:1.0.0-beta01"),
        gmaven_artifact("androidx.lifecycle:lifecycle-common:2.0.0-beta01"),
        gmaven_artifact("androidx.lifecycle:lifecycle-viewmodel:aar:2.0.0-beta01"),
        gmaven_artifact("androidx.core:core:aar:1.0.0-beta01"),
        gmaven_artifact("androidx.drawerlayout:drawerlayout:aar:1.0.0-beta01"),
        gmaven_artifact("androidx.constraintlayout:constraintlayout:aar:1.1.2"),
```

> It's worth mentioning that I don't need to add any extra dependencies to build that app if i get rid of the Kotlin file.

That sounds like the native rules have some magic to expand the deps. @jin is it possible for the macros to integrate with this

**Comment by Pmcneice** [comment]
Yep - adding those transitive dependencies gives me a successful build, brilliant!

I'll close this issue.

It would be *really* nice to have those dependencies automatically expanded just to keep things consistent with how the other existing rules behave (plus it's less config to write / maintain)

**Comment by jin** [comment]
Yeah, you shouldn't need to specify transitive deps with gmaven_rules/gmaven_artifact.

`gmaven_artifact` is a wrapper for `aar_import_external`, which is a repository rule that creates an  `aar_import` rule behind the scenes. aar_import's providers already pass on its transitive deps + exports. 

@hsyed thanks for fixing this, and it's great that there's a workaround. Let me try it again and see if we can fix the issue with missing transitive deps.

**Comment by Pmcneice** [comment]
Thanks both :)
