### ISSUE TITLE
kt_jvm_test should infer the test_class if unspecified.

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/rules_kotlin#150]
If the rule is named `FooTest` and the test file is `FooTest.java` or `FooTest.kt`, and the `test_class` is unspecified, the test rule should just work out that the test_class is `my.package.FooTest`.

> Note: it may be wrong if tests are specified differently in the `.kt` file, but that's totally fine, insofar as one can still override the `test_class`.

**Comment by hsyed** [comment]
Is it ok to just use the package name after translation directly ? My gut feel is that a normalising heuristic would be needed otherwise the java packages would need names like  `x.y.z.src.main.kotlin.com.acme.foo` to line up with the test class.

**Comment by cgruber** [comment]
Sadly it'll need normalizing. 

Thankfully, the normalizing heuristic would probably would walking backwards to `kotlin` or `java` and chopping it off from there, as nearly all projects use `src/main/java` or `src/main/kotlin`.  If those don't exist, `src` and `test` and maybe `javatest` as fallbacks.  

The nice thing, is that this is an inferred default, so it can be wrong - you'll just end up specifying manually if you use a non-standard pattern for folder structure.

I'm not sure if it's possible to ingest the source files either, but if so, both java and kotlin declare "package" so that might also be a possibility.

**Comment by ZacSweers** [comment]
I think this is still broken, as I'm having to still specify a `test_class` to make tests work in this dagger PR: https://github.com/google/dagger/pull/1805

**Comment by mgenov** [comment]
Seems broken. On my side I'm getting similar issue. 

```
Class not found: [kotlin.com.mycompany.mypackage.MyClassUnderTest]
```

```
kt_jvm_test(
    name = "MyClassUnderTest",
    srcs = glob([
        "src/test/kotlin/**/*.kt",
        "src/test/kotlin/**/*.java",
    ]),
    deps = [
        ":utils_lib",
        "//kotlin/libs:test_lib_deps",
    ],
)

```

**Comment by nkoroste** [comment]
+1 broken for me as well.

My failure didn't even include the class name:
```
Class not found: []
```

@cgruber can you re-open this issue please?

**Comment by aryeh-looker** [comment]
+1

**Comment by aryeh-looker** [comment]
This can happen in my experience if the package name is left out from the test kt file
