### ISSUE TITLE
Kotlin android.bzl uses the deprecated deps instead of exports, for no-source rules. 

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/rules_kotlin#152]
Bazel now asks that users use "exports=" instead of "deps=" for library rules without sources.  A call to native.android_library (android.bzl:31) uses this old pattern, and causes buidls to break on newer bazel installs.  This just needs to be swapped for "exports=" for that deps-only android  library.

**Comment by 10-10-11** [comment]
Fixed in #153
