### ISSUE TITLE
Working with kt_jvm_binary

### ISSUE THREAD

**Issue by jmmk** [bazelbuild/rules_kotlin#17]
I see in the docs:
> Note: This rule does not have all of the features found in java_binary. It is appropriate for building workspace utilities. java_binary should be preferred for release artefacts.

But it's not exactly clear what this means or what the preferred strategy is.

---

I have a code generation task written in Kotlin. I tried to use `kt_jvm_binary` along with `genrule`, but when running with `bazel build //my_genrule` I get a `No such file or directory` from bash.

```
# DOES NOT WORK
# Error: /bin/bash: bazel-out/host/bin/kt_bin: No such file or directory

kt_jvm_binary(
    main_class = "MainKt",
    name = "kt_bin",
    srcs = glob(["src/main/kotlin/**"]),
    resources = glob(["src/main/resources/**"]),
    deps = [
        ...
    ],
)

genrule(
        name = "some_genrule",
        tools = [":kt_bin"],
        cmd = "$(location :kt_bin) $(@D)",
        outs = [
                ...
        ],
)
```

My solution is to use `kt_jvm_library` + `java_binary` + `genrule`, where the `java_binary` is just a wrapper around the lib:

```
# DOES WORK!

kt_jvm_library(
    name = "kt_lib",
    srcs = glob(["src/main/kotlin/**"]),
    resources = glob(["src/main/resources/**"]),
    deps = [
        ...
    ],
)

java_binary(
        name = "java_bin",
        main_class = "MainKt",
        runtime_deps = [":kt_lib",],
)

genrule(
        name = "some_genrule",
        tools = [":java_bin"],
        cmd = "$(location :java_bin) $(@D)",
        outs = [
                ...
        ],
)
```

Is this expected?

**Comment by hsyed** [comment]
This use-case is what `kt_jvm_binary`  is meant for. You should be getting the location of the java wrapper script in the genrule. 

The approach you are using that works is valid, this is what you would use if you were also packaging and distributing the code generator.

**Comment by cgruber** [comment]
Can you clarify what you mean by "if you were also packaging the code generator?"  If your code generator is a java_plugin then it shouldn't be packaged up, or are you thinking of a generator in a different context?

**Comment by hsyed** [comment]
From a packaging perspective `java_binary` supports fat jars --i.e., `-deploy.jar` and proguard processing.  So in any context if those features are required than `java_binary` should be used. `java_plugin` could fall into this category as well -- for a kotlin annotation processor we would probably compile the kotlin files with `kt_jvm_library` and then wrap it with `java_plugin`. 

If the code generator is not a java_plugin and is only going to be used within the workspace than `kt_jvm_binary` removes the wrapping step. 

Perhaps we should consider a macro layer infant of the rules.

**Comment by cgruber** [comment]
Hmm.  Do we have concrete examples of using this non-java_plugin codegenerator that shouldn't have this wrapping?  

My main concern here is just the standard engineering one of "too many ways to do the same thing" - so if we can just use java_binary for these other cases, I'd rather we do.  But it's possible that I just haven't seen examples in practice that make using java_binary crappy enough to warrant the thinner rule. 

But if we can avoid the extra rule, we should try to, I think. (again, maybe it's justified, in which case, we should just be very sure to document aggressively what the differences are and when/why you'd use one over the other).

**Comment by hsyed** [comment]
@jmmk we use genrules internally to compile grpc stubs for kotlin. There is an example in the dagger app. Basically a jar with the extension `srcjar` in the srcs list will be unpacked and merged with the sources. Please reopen if your use case isn't covered.
