### ISSUE TITLE
Maybe need a kt_android_binary rule

### ISSUE THREAD

**Issue by act262** [bazelbuild/rules_kotlin#181]
I'm use `kt_android_library` delegate all source for binary, becase `android_binary` not support kotlin.

If application using ButterKnife , `kt_android_library` can not compile, because `butterknife` annotationProcessor need final constant `R.id.xx`.

So, is there any way?

```
android_binary(
    name = "app",

    # AndroidManifest
    manifest = "src/main/AndroidManifest.xml",

    multidex = 'native',
    dex_shards = 10,

    deps = [
        'wrapper'
    ]
)

# Load rules from kotlin support
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_android_library")

# Wrap all dependencies for final binary
kt_android_library(
...
)

```

**Comment by cgruber** [comment]
Can you not do all your building of things in the kt_android_library, and run butterknife on that library, and just use android_binary to do final dexing?

**Comment by act262** [comment]
That's exactly what I did, but in the application module , there using R.id.xx, not R2.id.xx
U can see my sample here.
[https://github.com/act262/gradle-to-bazel](https://github.com/act262/gradle-to-bazel)

**Comment by cgruber** [comment]
So, this is tricky, and I'm going to postpone this further, as it really requires a fully working kt_android_binary RULE, not a macro, which the kt_android_* stuff is.  That is to say, even kt_android_library delegates to a kt_jvm_library rule, and I can't see a way to properly get the final binary R.class generated in a world where we're using macros to wrap this. 

Once the android rules are "starlarkized" we can revisit this.  But for now, I'm making it closed-infeasible. 

Please feel free to re-open it once the android rules are out in starlark.
