### ISSUE TITLE
JAVA_HOME doesn't exist within the Builder's environment (even with --action_env) so java code is compiled with the embedded JDK

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/rules_kotlin#188]
Ran into the one case where compiling with JDK9+ (with target 1.8) and running on pre-JDK9 breaks (java.nio.ByteBuffer on 9 implements a non-covariant overload). 

In investigating, I discovered that within the working environment of the KotlinBuilder, JAVA_HOME is not set, regardless of the use of `--action_env` or other considerations. This causes the javac used to be the one from the embedded jdk, which in the case of use of java.nio.ByteBuffer, explosions at runtime with NoSuchMethod errors. 

The workaround is a simple cast, but there should be a way to specify the java environment to the kotlin rules, so that it does the right thing.

**Comment by davidsantiago** [comment]
Aha! I believe I was [struggling with this a week or two ago](https://github.com/bazelbuild/bazel/issues/8313), at least it was what confused the heck out of me to the point that I filed that issue. I was trying to build a Kotlin 1.3 project, but was getting [an error message](https://youtrack.jetbrains.com/issue/KT-28587) that appears related to jdk11 being used to build Kotlin 1.3. As I don't have JDK11 installed, but it appears to be what is used as the embedded JDK, I think your catch would explain what I was seeing.

**Comment by davidsantiago** [comment]
If you get a second, can you elaborate on the "simple cast" workaround? I looked at the KotlinBuilder source code, but can't figure out how to make use of this workaround.

**Comment by cgruber** [comment]
Sorry - you cast the `ByteBuffer` to just `Buffer`, which forces the compiler to link against the intended method.

**Comment by cgruber** [comment]
That doesn't solve all the problems, but it solves these coveriant overload issues.

**Comment by ThomasCJY** [comment]
Any update on this? Not being able to configure the java version correctly really tied our hands on the bazel migration.

**Comment by nkoroste** [comment]
Shouldn't Kotlin rules honor `--java_toolchain=@bazel_tools//tools/jdk:toolchain_java8` flag?

**Comment by ThomasCJY** [comment]
I have a tmp work around for this issue but it will breaks the cache since JAVA_HOME will be different for builder https://github.com/bazelbuild/rules_kotlin/pull/330 https://github.com/bazelbuild/bazel/issues/11382. To fix the root issue, we might need to pull in the embdded_jdk8 from bazel and use that during compilation.

**Comment by cgruber** [comment]
This has relevance in the modern context - we need to stop compiling java in the kotlin portion of the process, and this is largely achieved in John Garrish's retooling of the compilation pipeline. This depends on a stable ABI kotlin plugin. This is all in motion, but not there yet. Moving to 1.6 project.

**Comment by restingbull** [comment]
Obsolete.
