### ISSUE TITLE
Request: Status update and maybe some maintenance

### ISSUE THREAD

**Issue by davidsantiago** [bazelbuild/rules_kotlin#190]
I think like many, I'm incredibly excited for the new direction of the Kotlin rules under Google's maintainership. I think it's going to be great, and I'm incredibly appreciative that Google is taking on this rule set and supporting it for the rest of us. 

It would be great if we could get a status update, plan update, progress update, any additional details now available, or any other communique from Google about this stuff. It's been about 2 months since we last heard anything, and the word at that time was that the new rule set was expected in "mid 2019." I think at the most expansive, we might say that means somewhere in May-August, so we're already well into that window and near the actual middle of 2019. I'm just wondering if there's any clearer picture that we can make rough plans against. 

From my perspective, I've been trying to get a small Kotlin 1.3 project building on Bazel since Christmas. There were blockers other than the Kotlin rules, of course, but everything else has now been resolved and only the Kotlin rules remain (knock on wood). Judging from the issues and forks I see linked in them, there appear to be a number of people trying to get this working. 

So, followup question: If things are still a while off, can we get a maintenance pass done on the existing rules so that folks might get unblocked until the new ones arrive? There appear to be some forks and PRs floating around that at least some people are apparently having success with, and it would be great if a bit of maintenance/consolidation could get people unblocked a few months early. 

Thanks again.

**Comment by jin** [comment]
cc @thomaswk @git-str

**Comment by igorgatis** [comment]
I was about to open a issue titled "Is this project dead?". I sent a very straightforward PR (#187) about a week ago and got no response still. :(

**Comment by git-str** [comment]
Thanks for your and everyone else's interest and investment in the Kotlin rules. We're still focused right now on open sourcing our internal Kotlin rules, so we won't have the bandwidth to maintain any patches to the current rules. We're on track to open source the new rules in the coming weeks, so we hope that everyone can consolidate on the new rules soon.

**Comment by igorgatis** [comment]
Any updates?

**Comment by davidsantiago** [comment]
Just want to make sure you're aware of the heroic work that @cgruber has done, releasing working Kotlin 1.3 rules on [his fork](https://github.com/cgruber/rules_kotlin). He's been incredibly helpful and responsive on slack, and I've been using them for the past few weeks without problems. I assume they won't be source compatible with what is being worked on here, but it unblocked me.

**Comment by cgruber** [comment]
Per discussion at the end of #159, and per #204, we'll be merging in my fork shortly, and maintaining it here.  After it's in, we'll triage the existing issues and pull request, file some critical fix issues, and start actively maintaining it.  I'll be doing the lion's share of reviewing, to give the google team the space to finish their work, but we'll continue as if we weren't expecting new rules until plans firm up and we can hear otherwise.

I just released a final release in [my fork](http://github.com/cgruber/rules_kotlin) that added Bazel 1.0 support, so we should have a reasonable base to start fixing, tidying, improving.
