### ISSUE TITLE
Remove legacy use of ctx.outputs.executable predeclared output

### ISSUE THREAD

**Issue by puffnfresh** [bazelbuild/rules_kotlin#200]
I've been trying to figure out how to reference the shell script an not just the .jar file. I think this is not possible due to the special case of output, as mentioned here:

> As legacy behavior, executable rules have a special ctx.outputs.executable predeclared output. This file serves as the default executable if you do not specify one using DefaultInfo; it must not be used otherwise. This output mechanism is deprecated because it does not support customizing the executable file’s name at analysis time.

https://docs.bazel.build/versions/master/skylark/rules.html

It says legacy and deprecated so we should move away from it.

**Comment by cgruber** [comment]
Hey @restingbull - any thoughts on this one?
