### ISSUE TITLE
android_binary is broken because it's not allowed to depend on .jar artifacts

### ISSUE THREAD

**Issue by fishy** [bazelbuild/rules_kotlin#208]
Example code: https://github.com/fishy/onepwd

The current [master version](https://github.com/fishy/onepwd/tree/a24f4e9155a110e18699e756918eebd9618b163a) is using `rules_kotlin`@ 7543a917cda483c5856ec79b590343c9669eacd6 and it works. When I tried to upgrade it to newest master:

```
$ git diff
diff --git a/WORKSPACE b/WORKSPACE
index c25b6ea..236c6f5 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -7,12 +7,12 @@ android_sdk_repository(

 load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

-RULES_KOTLIN_VERSION = "7543a917cda483c5856ec79b590343c9669eacd6"
+RULES_KOTLIN_VERSION = "ab2f9f79912a35af3c1a07849d6fb457c2bfc54b"
 http_archive(
     name = "io_bazel_rules_kotlin",
     strip_prefix = "rules_kotlin-%s" % RULES_KOTLIN_VERSION,
     url = "https://github.com/bazelbuild/rules_kotlin/archive/%s.tar.gz" % RULES_KOTLIN_VERSION,
-    sha256 = "d335be363937ed62b5758cfdb33910ee52429835685345ef6b9f009c2bff9a9d",
+    sha256 = "1a18400bf92cba63554e2c71b9e74fa8569ab296e4954d232d5c643e19a2da02",
 )
 load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")
```

I got this error when building `:app`:

```
ERROR: /Users/fishy/work/onepwd/BUILD:23:12: in deps attribute of android_binary rule //:app: Dependencies on .jar artifacts are not allowed in Android binaries, please use a java_import to depend on external/com_github_jetbrains_kotlin/lib/kotlin-stdlib-sources.jar. If this is an implicit dependency then the rule that introduces it will need to be fixed to account for it correctly.
```

Using `bazel query 'allpaths(//:app, @com_github_jetbrains_kotlin//:kotlin-stdlib)' --output graph` gives me this dependency graph:

![dep](https://user-images.githubusercontent.com/78183/66626832-8afa3100-ebae-11e9-8f21-365b7fc4c8fe.png)

Another simpler android project have the same problem when upgraded `rules_kotlin` to ab2f9f79912a35af3c1a07849d6fb457c2bfc54b:

![dep2](https://user-images.githubusercontent.com/78183/66626945-ea584100-ebae-11e9-8304-7981c42dfbf1.png)

**Comment by cgruber** [comment]
On it.
