### ISSUE TITLE
Add android example app to farm initial issues and for e2e testing. 

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/rules_kotlin#21]
# Note: 

* The android rules only recognise `java_import` [See this issue in the old rule repo](https://github.com/hsyed/rules_kotlin_old/issues/8) and [upstream issue](https://github.com/bazelbuild/bazel/issues/4535).  `java_import` drops kotlin inline code but will be addressed [by this](https://github.com/bazelbuild/bazel/issues/4549).

# Purpose:

* End-to-End Tests for interaction with the native android rules.
* Test app for validating the intellij and android studio plugins.
* Farming issues with the rules that need to be made for android. This include discovering new macros that might be needed.

# Must:
* Exercise all appropriate rule orchestrations between the kt_jvm_* and the android rules.
* Stay within the android SDK as much as possible, we don't add the entire universe as external (maven) deps -- if we need a lot of external deps we should consider `bazel-deps` or `spotify/bazel-tools`. 
* Use an external version of the android SDK --e.g., `http_archive`.
* Wire up the android SDK in a way so that the recommended SDK version is used with the recommended Bazel version for CI testing -- in other words build flags, config settings and `select`.
* (in addition to android studio) be compilable and navigable in intellij CE or ultimate, at least the Kotlin code.
* Work without an IDE (this one might be obvious, but for all I know there is coupling with android studio).

**Comment by hsyed** [comment]
@davidstanke I'll assign this to you since I don't do any android development internally. I doubt much nitty gritty rule development work needs to occur, we might end up with some android specific macros. 

@cgruber are you interested in taking a stab at this one ? If we do need to add android specific macros all design questions will probably go to you.

**Comment by cgruber** [comment]
I'm in no position to put the time into this one, though part of me would
love to.  Let me see how I'm doing next week.
