### ISSUE TITLE
update to the new version of bazel -> 1.0.0

### ISSUE THREAD

**Issue by salim-boudriiya** [bazelbuild/rules_kotlin#213]
I have updated the bazel version from 0.29 to 1.0 and I have the following errors:

INFO: Writing tracer profile to '/private/var/tmp/_bazel_smba/424913bacc89aa4decf024fcb6d12f52/command.profile.gz'
ERROR: /private/var/tmp/_bazel_smba/424913bacc89aa4decf024fcb6d12f52/external/io_bazel_rules_kotlin/kotlin/internal/BUILD:31:1: in _kt_toolchain rule @io_bazel_rules_kotlin//kotlin/internal:default_toolchain_impl: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_smba/424913bacc89aa4decf024fcb6d12f52/external/io_bazel_rules_kotlin/kotlin/internal/BUILD", line 31
		_kt_toolchain(name = 'default_toolchain_impl')
	File "/private/var/tmp/_bazel_smba/424913bacc89aa4decf024fcb6d12f52/external/io_bazel_rules_kotlin/kotlin/internal/toolchains.bzl", line 46, in _kotlin_toolchain_impl
		dict(language_version = ctx.attr.lang..., <7 more arguments>)
	File "/private/var/tmp/_bazel_smba/424913bacc89aa4decf024fcb6d12f52/external/io_bazel_rules_kotlin/kotlin/internal/toolchains.bzl", line 53, in dict
		java_common.create_provider(compile_time_jars = ctx.files.jv..., <2 more arguments>)
type 'java_common' has no method create_provider()
ERROR: Analysis of target '//src/main:bazel_app1' failed; build aborted: Analysis of target '@io_bazel_rules_kotlin//kotlin/internal:default_toolchain_impl' failed; build aborted

Can you help me to resolve it please

Best regards

**Comment by cgruber** [comment]
Hi.  What version of the rules are you using?  The master branch doesn't currently have a recent release, and 1.0 compatibility is not available in any of the previous releases. Are you using an older version?

Just to note, there is a key regression we're trying to track down, after which we will be releasing a version from this branch.  That version is expected to be compatible with 1.0.0.

**Comment by salim-boudriiya** [comment]
hi,

Iam using this rule version:

rules_kotlin_version = "legacy-modded-1_0_0-01"

Best regards.

**Comment by salim-boudriiya** [comment]
hi @cgruber,

Please, could you let me know once you have solved that error.

Best Regards

**Comment by cgruber** [comment]
Critical fixes are either in HEAD or in review. Should release in the next day or three.
