### ISSUE TITLE
Implementations of `idl_parcelables` not found during compilation of generated AIDL java.

### ISSUE THREAD

**Issue by jasonwyatt** [bazelbuild/rules_kotlin#228]
I've found a bug in `kt_android_library` dealing with AIDL interfaces and parcelables.  The generated Java for AIDL interfaces referencing parcelables defined within `idl_parcelables` does not compile due to the fact that the parcelable's implementation is not located in a location visible to the generated Java.

I've verified that an analogous java `android_library` target compiles fine, and the issue seems to lie in the implementation of `kt_android_library`. (and whether the implementation of the parcelable is written in Java or in Kotlin is immaterial)

Here's a minimal repro case that includes both a failing `kt_android_library` example, as well as a succeeding `android_library` example:
https://github.com/jasonwyatt/rules_kotlin-idl_parcelables_bug

**Comment by cgruber** [comment]
At this point so much has changed that I'm going to close this and we can re-examine it in the current infra for 1.6 if it's still occurring.

**Comment by jasonwyatt** [comment]
This still occurs in 1.6.
