### ISSUE TITLE
Missing runtime dependency on kotlin-stdlib-jdk8 using legacy-1.3.0-rc1

### ISSUE THREAD

**Issue by rtrx** [bazelbuild/rules_kotlin#230]
I'm using Kotlin's [`Stream<T>.asSequence`] (https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/as-sequence.html) in a library that compiles successfully, but hits a `ClassNotFoundException` at runtime:
```
  java.lang.NoClassDefFoundError: kotlin/streams/jdk8/StreamsKt
  ...
  Caused by: java.lang.ClassNotFoundException: kotlin.streams.jdk8.StreamsKt
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 26 more
```
**Adding a dep or runtime_dep on `"@com_github_jetbrains_kotlin//:kotlin-stdlib-jdk8",` to my `kt_jvm_library` target fixes the issue, but I don't think this should be needed explicitly.**

I'm using the newest version of bazelbuild/rules_kotlin based on the [README](https://github.com/bazelbuild/rules_kotlin/blob/master/README.md) (see WORKSPACE snippet below). The offending code snippet is:
```
# CodeSnippet.kt
dynamoDbClient.queryPaginator(queryRequest).items().stream().asSequence().map { ... }
```

```
# BUILD.bazel
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "CodeSnippet",
    srcs = ["CodeSnippet.kt"],
    deps = [
        # !!! Shouldn't be required, but fails at runtime if omitted !!!
        "@com_github_jetbrains_kotlin//:kotlin-stdlib-jdk8",
    ],
)
```

```
# WORKSPACE
rules_kotlin_version = "legacy-1.3.0-rc1"
rules_kotlin_sha = "9de078258235ea48021830b1669bbbb678d7c3bdffd3435f4c0817c921a88e42"

http_archive(
    name = "io_bazel_rules_kotlin",
    sha256 = rules_kotlin_sha,
    strip_prefix = "rules_kotlin-%s" % rules_kotlin_version,
    type = "zip",
    urls = ["https://github.com/bazelbuild/rules_kotlin/archive/%s.zip" % rules_kotlin_version],
)

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")
kotlin_repositories()
kt_register_toolchains()
```

Any ideas about what could be causing this issue? My WORKSPACE is configured exactly like the example in [README](https://github.com/bazelbuild/rules_kotlin/blob/master/README.md), so perhaps I'm missing some other registration step?

**Comment by cgruber** [comment]
So jdk8 isn't added as an automatic dependency, because a lot of users are using kotlin with android, and not all android users can use streams, so we don't "pollute" their classpaths with java8-isms. 

That said, maybe I can do something with the toolchains, adding it if the right jdk target version is specified.  I'll look into it .

**Comment by cgruber** [comment]
I'm not going to promise this for the 1.3 legacy release, as there is a simple workaround of adding the dep.  But I'll make it a feature for 1.4.

**Comment by cgruber** [comment]
For now, closing this, as we haven't really come to grips with what we're interested in bundling with the rule (in terms of classpath) and we have a bunch of different thoughts on this under discussion. The issue as-phrased is quite obsolete, and we're not supporting 1.3 anymore.
