### ISSUE TITLE
kt_jvm_library failing if no srcs are provided

### ISSUE THREAD

**Issue by nkoroste** [bazelbuild/rules_kotlin#232]
Expected `kt_jvm_library` to behave similar to `java_library` where `srcs` attribute is optional. However, it will fail with the following error:
```
io_bazel_rules_kotlin/kotlin/internal/jvm/compile.bzl", line 154, in kt_jvm_compile_action
		fail("no sources provided")
```
This was discovered when writing a genrule to support SQLDelight which is usually a kotlin target

**Comment by cgruber** [comment]
Yeah - I need to fix this. The problem underlying is that kotlinc barfs on no sources, but the library definitely needs to handle that case.  The complication is that sometimes there are sources, but no kotlin sources (java only), so there are a few fancy tricks going on here. I'll prioritize this.

**Comment by restingbull** [comment]
qq -- what purpose does a kt_jvm_library without srcs or exports provide?

**Comment by johnheroy** [comment]
> qq -- what purpose does a kt_jvm_library without srcs or exports provide?

Not sure about not having srcs or exports, but it'd be nice to have exports but not srcs in some cases.
