### ISSUE TITLE
Stop doing a separate java compilation (forcing java stubs)

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/rules_kotlin#266]
The rules do a separate java compilation, which requires stub generation, on mixed-source compile jobs. This can, in extreme cases, result in lots of kotlin files generating stubs just to compile a java file (which may not need them), and then the whole kotlin compilation job needs to happen after that, consuming the output of the java compilation. 

The benefits seem ethereal, and the worst-cases add a huge pre-step without payoff.  We need to stop this process, and just run a normal compilation.

Note - we'll lose some benefits, namely things like error-prone for the java files. We might do something post-process about that.

**Comment by restingbull** [comment]
Marking obsolete after moving to java toolchain.
