### ISSUE TITLE
Allow users to configure kotlinc logging verbosity and the like

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/rules_kotlin#277]
At present, bazel doesn't control the tools' logging/verbosity. Add a facility (either flags, or custom configs, or something else) to let users adjust this.

This can have particular performance benefits, as logging to fine-grained can slow down builds waiting for I/O.

**Comment by cgruber** [comment]
This is a tracking bug to make sure that one of the outcomes of #23 includes this use-case.

**Comment by restingbull** [comment]
There is already basic support baked in for kotlin compilation steps:

--define=kt_timing=1 will report the high level time taken for each step:
Task timings for //lib:lib_kt (total: 2153 ms):
|   * expand sources: 0 ms
|   * kapt (): 0 ms
|   * compile classes: 1949 ms
|     * kotlinc: 1948 ms
|     * javac: 0 ms
|   * create jar: 2 ms
|   * produce src jar: 8 ms
|   * generate jdeps: 192 ms
