### ISSUE TITLE
sha256 of rules_kotlin_release.tgz for 1.4.0-rc3 release doesn't match

### ISSUE THREAD

**Issue by SanjayVas** [bazelbuild/rules_kotlin#334]
The [`rules_kotlin_release.tgz.sha256`](https://github.com/bazelbuild/rules_kotlin/releases/download/legacy-1.4.0-rc3/rules_kotlin_release.tgz.sha256) asset for 1.4.0-rc3 lists `560a0dba4386439d89c94a8242d34dbbb817829acf291fef7a8222c9be2c96da` as the sum, but the actual sha256 sum of [`rules_kotlin_release.tgz`](https://github.com/bazelbuild/rules_kotlin/releases/download/legacy-1.4.0-rc3/rules_kotlin_release.tgz) is `da0e6e1543fcc79e93d4d93c3333378f3bd5d29e82c1bc2518de0dbe048e6598`.

**Comment by cgruber** [comment]
Ugh. Fixed. Sorry about that. I uploaded the wrong file. :/  Embarassing.
