### ISSUE TITLE
Allow users to set javac arguments

### ISSUE THREAD

**Issue by zls88** [bazelbuild/rules_kotlin#357]
Poking around `kotlinc` it looks like there's a `-Xjavac-arguments` flag. Is there any way that we can expose this in the rules like `kt_jvm_library`? Otherwise I'm not sure how to enable e.g. [NullAway](https://github.com/uber/NullAway).

**Comment by restingbull** [comment]
https://github.com/bazelbuild/rules_kotlin/issues/396
