### ISSUE TITLE
Problems using rules_kotlin as local repository

### ISSUE THREAD

**Issue by jeffzoch** [bazelbuild/rules_kotlin#369]
I am trying to use rules_kotlin via `local_repository` and am running into trouble. I followed the readme and added the following in my `WORKSPACE`:

```
local_repository(
    name = "io_bazel_rules_kotlin",
    path = "../rules_kotlin",
)

load("@io_bazel_rules_kotlin//kotlin:dependencies.bzl", "kt_download_local_dev_dependencies")
kt_download_local_dev_dependencies()
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")
KOTLIN_VERSION = "1.4.10"
KOTLINC_RELEASE_SHA = "bb1a21d70e521a01ae104e99a082a6e7bb58699b86347049da521d175d0dace7"

KOTLINC_RELEASE = {
    "urls": [
        "https://github.com/JetBrains/kotlin/releases/download/v{v}/kotlin-compiler-{v}.zip".format(v = KOTLIN_VERSION),
    ],
    "sha256": KOTLINC_RELEASE_SHA,
}

kotlin_repositories(compiler_release = KOTLINC_RELEASE)

kt_register_toolchains()
```

When I build though I get 
`ERROR: /private/var/tmp/_bazel_j.zoch/8bdf7aad5539a314ee98a49e42674806/external/io_bazel_rules_kotlin/third_party/BUILD:57:12: @io_bazel_rules_kotlin//third_party:jarjar_runner depends on @kotlin_rules_maven//:org_pantsbuild_jarjar in repository @kotlin_rules_maven which failed to fetch. no such package '@kotlin_rules_maven//': type 'string' is not iterable`

I tried updating bazel to 3.4.1 and that did not help

**Comment by rockwotj** [comment]
Kotlin version 1.4 is not supported yet. See #363

**Comment by jeffzoch** [comment]
@rockwotj even if I downgrade kotlin (and use the original toolchain) this still happens

**Comment by restingbull** [comment]
What commit are you pulling from?

There may have been a merge issue.

**Comment by cgruber** [comment]
If you're not pulling from the release artifact (the .tgz) then you need to follow the instructions here in the readme: https://github.com/bazelbuild/rules_kotlin/blob/master/README.md#development-setup-guide
