### ISSUE TITLE
Ability to pass compiler arguments in either toolchain or build rule

### ISSUE THREAD

**Issue by therealmik** [bazelbuild/rules_kotlin#373]
I have a mixed kotlin/java project that needs the ability to pass the `-java-parameters` argument to kolinc to work properly (Apache Beam Schemas need this feature).

There doesn't seem to be a way to specify this argument in either the toolchain rule or kt_jvm_library rule.

**Comment by restingbull** [comment]
See https://github.com/bazelbuild/rules_kotlin/issues/396
