### ISSUE TITLE
Mixed Java + Kotlin kt_jvm_tests throw exception

### ISSUE THREAD

**Issue by jeffzoch** [bazelbuild/rules_kotlin#414]
`kt_jvm_test has to declare 'JavaConfiguration' as a required fragment in target configuration in order to access it.` is thrown when kt_jvm_test is used with both kotlin and java test files. This is on the latest commit with `experimental_use_abi_jars = True`. Setting it to false seems to work

**Comment by restingbull** [comment]
Provide a sample build file?

@jongerrish -- I'm thinking you might have fixed this already?

**Comment by jongerrish** [comment]
No, I didn't come across this, but it looks like kt_jvm_test is just missing

```
    fragments = ["java"],  # Required fragments of the target configuration
    host_fragments = ["java"],  # Required fragments of the host configuration
```

from the rule declaration.
