### ISSUE TITLE
Implement strict deps for Kotlin

### ISSUE THREAD

**Issue by jongerrish** [bazelbuild/rules_kotlin#419]
Bazel Java rules utilize a compiler plugin to enforce that rules explicitly declare direct dependencies. The compiler plugin will fail if a symbol is provided through transitive dependencies only providing the buildozer command to add the missing dependency.

Kotlin should support the equivalent functionality which we can implement using a Kotlin compiler plugin.

Since https://github.com/bazelbuild/rules_kotlin/pull/415 we now pass in a builder flag `--direct_dependencies` of the jars containing classes declared in the rules `deps` attribute. We can check every symbol referenced in the source should be present in these jars. If not, we can find containing jar from `--classpath` jars and extract the origin rule to provide the buildozer command to add the missing deps.

**Comment by Kernald** [comment]
This looks like a duplicate of #265

**Comment by jongerrish** [comment]
Implemented this as a toolchain parameter:

experimental_strict_kotlin_deps with values "off", "warn", "error"
