### ISSUE TITLE
Direction of Opt-In API

### ISSUE THREAD

**Issue by jeffzoch** [bazelbuild/rules_kotlin#422]
Based on @restingbull concerns in #398, we should discuss how we want to handle Opt-In. For context, this flag  https://kotlinlang.org/docs/reference/opt-in-requirements.html can be made required by library users who want to provide experimental apis. The most common use-cases are for coroutines apis and jetpack compose. Since any library author can create this I'd think adding one off flags for each one would be superfluous and instead we just add an "opt-in" flag like in #398 that allows you to define a list of strings.

Opt-in as far as I know isnt problematic in that it would cause compilation issues for other targets - it merely allows you to access apis otherwise provide warnings.

**Comment by restingbull** [comment]
## Proposed API
kt_compiler_options(
   opt_in = [
        "boo.bar.Baz"
   ]
)
## Open Design Questions

- Should this be limited to library level options?
   - Pro: Given the transitory nature and intent of optin (e.g. the api may change at anytime, opt_in annotations should be temporary), requiring them to be close to code ensures easier maintenance.
  -  Pro: Supports the rule over toolchain option merging strategy.
   - Con: For opt_ins in broad use, this presents a larger maintenance burden.
- Should there be validation for well-known, unused options? (e.g. kotlin finally blesses an API)
- How should opt_ins be merged, given both toolchain and rule option definitions? https://github.com/bazelbuild/rules_kotlin/pull/418 presents the merging strategy of rule over toolchain, no union. This may not be ideal for opt_ins.

**Comment by restingbull** [comment]
@Bencodes, @jeffzoch, @cgruber, @jongerrish  -- thoughts?

**Comment by jeffzoch** [comment]
> Should there be validation for well-known, unused options? 
Do you mean *used* options instead of unused? If so, I think that while reasonable it might be strange as a user to see some available by default and others must be specified. I don't feel strongly about this though.

> How should opt_ins be merged, given both toolchain and rule option definitions? #418 presents the merging strategy of rule over toolchain, no union. This may not be ideal for opt_ins.
I think they should be unioned personally as it would be easier to drop into a toolchain that my whole repo is free to use coroutines experimental apis, forcing that specification on every rule would be less ideal (though explicit so there is strength in that). Again, I dont feel super strongly and can be convinced either way. If I had to vote Id say lets merge them

**Comment by restingbull** [comment]
> > Should there be validation for well-known, unused options?
> 
> Do you mean _used_ options instead of unused? If so, I think that while reasonable it might be strange as a user to see some available by default and others must be specified. I don't feel strongly about this though.
unused -- e.g. they finally launch "x" feature, so the opt-in for "x" becomes unnecessary.

> 
> > How should opt_ins be merged, given both toolchain and rule option definitions? #418 presents the merging strategy of rule over toolchain, no union. This may not be ideal for opt_ins.
> 
> I think they should be unioned personally as it would be easier to drop into a toolchain that my whole repo is free to use coroutines experimental apis, forcing that specification on every rule would be less ideal (though explicit so there is strength in that). Again, I dont feel super strongly and can be convinced either way. If I had to vote Id say lets merge them
> 
> Edit: Really, I think that as long as the choice is well-documented it doesn't matter too much. "Rule over toolchain" has the nice property that if we decided we did not like it and switched to a merge strategy it would be a straight-forward breakage for users - the reverse is not true. If we went from merge strategy to R.O.T. then a user may accidentally let additional flags slip into builds. Finally, consistency matters. So, if other rules use a particular strategy it may make sense to be consistent despite the extra verbosity.

I could make the argument that we should only put `opt_ins` on rules. With a rule specific options rule (say that 3 times fast. :p), sharing a set of options becomes trivial and more explicit (of which I am generally in favor -- configuration over convention where it is not burdensome). Thoughts?

**Comment by jeffzoch** [comment]
@restingbull yeah I think thats fair. I like the idea of it being separate from kotlinc overrides

**Comment by restingbull** [comment]
Alright, it's been 9 days and we are agreeing.

Update https://github.com/bazelbuild/rules_kotlin/pull/398 to match the discussion?

**Comment by jeffzoch** [comment]
@restingbull sure thing - sorry had been on vacation. Ill try to do it in the next week
