### ISSUE TITLE
Upgrading to 1.5.0-alpha2 throws a jdeps error

### ISSUE THREAD

**Issue by pratik-brex** [bazelbuild/rules_kotlin#440]
This is the error from sandbox after upgrading to 1.5.0-alpha-2

```Cannot locate  ECD record in singlejar_local: src/tools/singlejar/input_jar.cc:52: Cannot locate  ECD record in bazel-out/darwin-fastbuild/bin/redacted/application.jdeps```

**Comment by restingbull** [comment]
Does this happen in alpha-3?

**Comment by Bencodes** [comment]
We just encountered something similar when testing against `alpha3`. It looks like if there aren't Kotlin sources in a Kotlin target, a jdep output isn't being generated.

**Comment by restingbull** [comment]
@jongerrish?

**Comment by jongerrish** [comment]
I'll take a look this weekend. @pratik-brex do you have more log info / repro case you can share?

What do you have for your tool chain configuration? Are you enabling experimental_use_abi_jars?

```
define_kt_toolchain(
    experimental_use_abi_jars = True,
   ...
)
```

**Comment by jeffzoch** [comment]
@jongerrish confirm ran into the same issue. We dont use any flags on the toolchain configuration - all defaults and we hit this. No jdeps generated if kotlin sources didnt exist. Adding an empty kotlin class fixed it

**Comment by jongerrish** [comment]
@jeffzoch - awesome, thanks, sounds like its easy to repro. I'll get a fix in on Sunday.
