### ISSUE TITLE
Question: PR adding an example of an Android app using Jetpack Compose

### ISSUE THREAD

**Issue by alexjlockwood** [bazelbuild/rules_kotlin#445]
Would you accept a PR that adds an example on how to build a simple Hello World Android app using Jetpack Compose (under `examples/compose`)?

**Comment by Bencodes** [comment]
For those that are interested in using Jetpack Compose, I threw together a quick example to showcase that it's possible https://github.com/Bencodes/bazel_jetpack_compose_example

**Comment by restingbull** [comment]
Yes.

**Comment by alexjlockwood** [comment]
Thanks for the review @restingbull!
