### ISSUE TITLE
Do not issue "worker" warning when compiling with a Remote Build Environment

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/rules_kotlin#453]
When running a build using a remote build environment, such as [buildbarn](https://github.com/buildbarn), the error message `HINT: KotlinCompile will compile faster if you run: echo "build --strategy=KotlinCompile=worker" >>~/.bazelrc` isn't actionable. Could this warning be disabled or hidden behind a flag?

**Comment by restingbull** [comment]
I'm thinking the note isn't that useful, tbh.
