### ISSUE TITLE
Some variables are not substituted in test script template

### ISSUE THREAD

**Issue by jameslan** [bazelbuild/rules_kotlin#455]
When running the test, the beginning of the output is

>/private/var/tmp/_bazel_james/80be99c14e264815cdc2aecde45dcb13/sandbox/darwin-sandbox/6/execroot/xxxx/bazel-out/darwin-fastbuild/bin/javatests/com/xxxx/futureExtensionTest.runfiles/xxxx/javatests/com/xxxx/futureExtensionTest: line 112: fg: no job control

Line 112 of this file is

```
%test_runtime_classpath_file%
```

Another variable is `needs_runfiles`:

```
if [[ "$SINGLEJAR" != 1 || "%needs_runfiles%" == 1 ]]; then
```

**Comment by bootstraponline** [comment]
I'm seeing the same error using `Kotlin Rules 1.5.0 (Alpha 3)`. `kt_jvm_test` is broken and it complains about `fg: no job control`. 

```bazel
kt_jvm_test(
    name = "test",
    srcs = [
        "MyTest.kt",
    ],
    test_class = "example.MyTest",
    deps = [
        "@maven//:com_google_truth_truth_1_1",
        "@maven//:junit_junit_4_13_1",
    ],
)
```

>/private/var/tmp/_bazel_/21e50dda0d1a619583f75522a2389119/sandbox/darwin-sandbox/178/execroot/code/bazel-out/darwin-fastbuild/bin/foo/foo/src/test/test.runfiles/foo/foo/foo/src/test/test: line 112: fg: no job control

```bash
# A file storing the test's runtime classpath, excluding the test support.
# The file is read by the persistent test runner. The jars inside the file are
# loaded dynamically for every test run into a custom classloader.
%test_runtime_classpath_file%
```

@jongerrish @Bencodes Are you able to reproduce the issue? Being unable to run tests is a blocker for us.

**Comment by Bencodes** [comment]
This hasn't been an issue for us in our repo (using master rules kotlin + Bazel 4.0.0). Are you able to reproduce this in a sample project?

**Comment by bootstraponline** [comment]
Here's an example project that reproduces the error reported in this issue. The test defined in the buildfile has an incorrect `test_class`, and that seems to trigger the `fg: no job control`

- https://github.com/bootstraponline/rules_kotlin_455

```
$ git clone git@github.com:bootstraponline/rules_kotlin_455.git
$ bazel test //test/a:test
INFO: Analyzed target //test/a:test (1 packages loaded, 2 targets configured).
INFO: Found 1 test target...
FAIL: //test/a:test (see /private/var/tmp/_bazel_mac/201af91226305fcd40b4ad1bf557ecdf/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/test/a/test/test.log)
Target //test/a:test up-to-date:
  bazel-bin/test/a/test.jar
  bazel-bin/test/a/test.jdeps
INFO: Elapsed time: 0.983s, Critical Path: 0.76s
INFO: 3 processes: 1 internal, 2 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 3 total actions
//test/a:test                                                            FAILED in 0.6s
  /private/var/tmp/_bazel_mac/201af91226305fcd40b4ad1bf557ecdf/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/test/a/test/test.log

INFO: Build completed, 1 test FAILED, 3 total actions
```


```bash
$ cat /private/var/tmp/_bazel_mac/201af91226305fcd40b4ad1bf557ecdf/execroot/__main__/bazel-out/darwin-fastbuild/testlogs/test/a/test/test.log
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //test/a:test
-----------------------------------------------------------------------------
/private/var/tmp/_bazel_mac/201af91226305fcd40b4ad1bf557ecdf/sandbox/darwin-sandbox/34/execroot/__main__/bazel-out/darwin-fastbuild/bin/test/a/test.runfiles/__main__/test/a/test: line 112: fg: no job control
Class not found: [example.ATest]

BazelTestRunner exiting with a return value of 2
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.

-- JVM shutdown starting at 2021-02-24 14:47:01 --
```



If I update the class, then the error goes away.

```diff
diff --git a/test/a/BUILD.bazel b/test/a/BUILD.bazel
index 106f892..69c3820 100644
--- a/test/a/BUILD.bazel
+++ b/test/a/BUILD.bazel
@@ -5,7 +5,7 @@ kt_jvm_test(
     srcs = [
         "ATest.kt",
     ],
-    test_class = "example.ATest",
+    test_class = "a.ATest",
     deps = [
         "@maven//:junit_junit_4_13_1",
     ],
```

Is this expected? Can rules_kotlin handle this case better without triggering `fg: no job control`?

**Comment by Bencodes** [comment]
This behavior looks to be expected. If you look at the implementation for this test rule, `kt_jvm_junit_test_impl` trusts the values that you provide for `main_class` and does not do any special validation on it. https://github.com/bazelbuild/rules_kotlin/blob/04785887f385b1f2294cd988b438c2dafad82e5d/kotlin/internal/jvm/impl.bzl#L211-L221

**Comment by bootstraponline** [comment]
Maybe this is a feature request to improve the error messaging? The error message `fg: no job control` is a bit confusing.

**Comment by Bencodes** [comment]
These rules are just expanding the `java_stub_template.txt` [defined in bazel](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt). This is the same template that `java_test` uses to execute jvm tests. You would have to file a ticket against core Bazel.

**Comment by bootstraponline** [comment]
Makes sense. Thanks for the detailed information. I think this issue can be closed then?

**Comment by jameslan** [comment]
> You would have to file a ticket against core Bazel.

How can this an issue of Java support in Bazel? The template expects the rule to provide substitution, to support singlejar here. And when you use `java_test`, it is replaced correctly and there's no error message.

Since `rules_kotlin` chooses to use this template but not use singlejar, it should provide empty content to remove it from the file, instead of leaving illegal syntax there.
