### ISSUE TITLE
Intellij/Bazel doesn't actually execute the kotlin rules when "build" is pressed

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/rules_kotlin#46]
Not sure if this is an issue here or in the intellij integration, but:

Repro steps:
1. Set up a project to use rules_kotlin per the readme instructions
2. Import normally into intellij using "import bazel project" 
3. Press the build button (project builds normally and succeeds).
4. Introduce a compile error into the kotlin code.
5. Press build button 
6. Build from the command-line.

Symptoms:
After step 3, all looks well, the project is indexed and seems to build properly.
After step 5, the same exact results occur, even though there's a compiler error.  The project seems to build properly.
After step 6, the build does fail, showing that at least the compiler is catching it when executed through blaze directly.

Note: Adding a java compile error to a java target in the project DOES result in a failed build through the intellij integration. 

So it does seem to me that somehow the kotlin rules are not being executed even though they're part of the .bazelproject workspace definition. 

I've tried this with //src/... or //src/main/kotlin/path/to/library:target specifications, and none of them work.  The project definitely indexes fine, and intellij itself does (once the kotlin project config is set up) catch the error with its analyzers.

**Comment by hsyed** [comment]
@cgruber The intellij plugin is donkeys years old :D You can install one of [these](https://github.com/hsyed/intellij/releases) it's ponys years old.

This [PR](https://github.com/bazelbuild/intellij/pull/217) has been merged internally at Google I am told but the master has not been updated. 

I have mountains of code sitting in branches waiting to be merged -- could you make some noise internally so that the internal branches track the gh repo rather than the other way around ? :D

**Comment by hsyed** [comment]
Did you add the bazelproject directives (see the .bazelproject in this repo). 

fyi: `additional_languages`  will be deprecated soon with my recent changes. all intellij configuration will be derived from the repo.  [this](https://github.com/bazelbuild/rules_kotlin/blob/ac84ceb3ac670fb5d64c2e83f7940299bc3873c0/kotlin/internal/bootstrap.bzl#L36-L50) gets serialized as a json file and picked up by the intellij plugin transparently -- of course I'm blocked on my previous pr going in and the code being synced back into master

**Comment by hsyed** [comment]
Assuming you have the correct plugin and are still being the problem, are you introducing errors into the Kotlin builder source code ? This isn't a first class Kotlin target -- it has to first be compiled via a bootstrap macro. I've added a `kt_jvm_library` as a convenience to work with it in the IDE.  If you add an error here it will fail in the bootstrap macro.

**Comment by hsyed** [comment]
Aha that is archaic, there isn't really any "support" in the plugin you have loaded. it's just a stub really. The version I linked is built against GH master and has the PR I linked. It has all the features you need working. 

@brendandouglas manages the intellij codebase.

**Comment by cgruber** [comment]
Ok. Got it. Using your more recent plugin worked like a charm.  

In the mean-time, I'll update the readme to note that you need a recent ijwb plugin to support kotlin.  It did recognize the langauge in additional_languages, but that's about it.
