### ISSUE TITLE
aar as kt_jvm_library dependency

### ISSUE THREAD

**Issue by kafji** [bazelbuild/rules_kotlin#48]
Hi. I want to compile Kotlin file with aar.

KotlinActivity.kt:
```
import android.support.v7.app.AppCompatActivity

class KotlinActivity : AppCompatActivity() {
}
```

Target:
```
java_import(
    name = "sdk",
    neverlink = 1,
    jars = ["//tools/defaults:android_jar"],
)

kt_jvm_library(
    name = main_kt,
    srcs = ["KotlinActivity.kt"],
    deps = ["@appcompat_v7//aar" + "sdk"],
 )
```

But when I build `main_kt` I got an error as this:
```
error: supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class android.support.v7.app.AppCompatActivity, unresolved supertypes: android.support.v4.app.FragmentActivity, android.support.v4.app.TaskStackBuilder.SupportParentable
    class android.support.v7.app.ActionBarDrawerToggle, unresolved supertypes: android.support.v4.widget.DrawerLayout.DrawerListener
```

I can achieve this using pubref's kotlin_android_library.

Is it possible to include aar as dependency for kt_jvm_library or maybe is there a replacement rule for pubref's kotlin_android_library?

Thanks.

**Comment by hsyed** [comment]
I don't develop on Android, So I need some feedback from upstream bazel devs who maintain the android rules for the best way integrate with the android. 

My advice would be to use kt_jvm_library to compile your Kotlin srcs and then feed those into Android or Java rules for the time being.

**Comment by ahumesky** [comment]
The aar_import rule provides a JavaInfo provider:
https://github.com/bazelbuild/bazel/blob/3a7b8bc2abeaf8b8647c037bed1dd5fd73b8392b/src/main/java/com/google/devtools/build/lib/rules/android/AarImport.java#L199

which is the same thing that java_import does:
https://github.com/bazelbuild/bazel/blob/3a7b8bc2abeaf8b8647c037bed1dd5fd73b8392b/src/main/java/com/google/devtools/build/lib/rules/java/JavaImport.java#L177

Does having a java_import in the deps of a kt_jvm_library work? E.g, if you extend just Activity, which would come from the android.jar through the java_import, does that work?

**Comment by kafji** [comment]
@hsyed that's my plan.

@ahumesky it does works.

I've solved my problem. It was that @appcompat_v7//aar doesn't include its transitive dependencies. I.e. support-fragment and support-core-ui.

**Comment by ahumesky** [comment]
Glad you were able to find a solution. Transitive dependency management is something that we're working to improve. In the meantime, depending on your needs, there are temporary workaround like https://github.com/aj-michael/gmaven_rules which set up the transitive dependencies for you.

**Comment by kafji** [comment]
@ahumesky I was using that. I guess it's not working because the transitive dependencies are declared on `deps` attribute when it should be on `exports`.

**Comment by ahumesky** [comment]
Which version of bazel are you using? I believe that this was fixed with https://github.com/bazelbuild/bazel/issues/4472

**Comment by kafji** [comment]
@ahumesky 

```
Build label: 0.11.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue May 14 07:48:23 +50148 (1520362424903)
Build timestamp: 1520362424903
Build timestamp as int: 1520362424903
```

Repro https://github.com/kafji/bazel48

**Comment by ahumesky** [comment]
Thanks for the repro, looks like there's still something going on with deps vs exports.
