### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by jeffzoch** [bazelbuild/rules_kotlin#539]
Any idea when the next release is coming? my company only uses the official releases and I know they were blocked for awhile due to a CI issue

**Comment by rockwotj** [comment]
@cgruber any updates here? I notice the milestone you made is due today.

**Comment by cgruber** [comment]
Yep. Delayed, though not, like weeks. Probably next week. I'll try to get
some of it done this weekend, but no promises.

**Comment by jeffzoch** [comment]
@cgruber sorry I was on PTO for a few weeks - Any update on releases? If there is a blocker we can help on I'd love to help
