### ISSUE TITLE
Add lombok plugin

### ISSUE THREAD

**Issue by jeffzoch** [bazelbuild/rules_kotlin#575]
https://kotlinlang.org/docs/lombok.html would be great to have available in the rules like we do for other plugins packaged by the kotlin compiler.

**Comment by cgruber** [comment]
In theory, any kotlinc plugin should be workable with the rules as-is, by exposing a plugin rule and exporting it. Can you please see if that can work for you at all? Including it in the pre-packaged stuff seems out of scope, but it would be good to know if it breaks for some reason.
