### ISSUE TITLE
Are there plans to make a kt_android_library rule? 

### ISSUE THREAD

**Issue by grandstaish** [bazelbuild/rules_kotlin#58]
The current rules seem to be limited to the jvm so they can't be used for building an Android lib. Is a `kt_android_library` rule something you want but haven't done yet, or is this not the right direction at all?

**Comment by hsyed** [comment]
Android should work you will need to write some macros for your project. Basically you build a kotlin jar useing the rules here and you then glue / wrap them into the android rules. In the grand scheme of things writing these macros is a small amount of work in setting up a mono repo with bazel.

I would love to work on this to provide “official” android support but I need support from Google (@davidstanke) on this one as it is a significant amount of time and we don’t use android internally. Google is best placed to design the structure of these rules / macros for the long term.

Integration tests would be required and depending on how the rules are designed some changes might be needed in the android rules in bazel core.

**Comment by davidstanke** [comment]
Hey hey! I've actually moved to a slightly different role at Google, so IDK if I can do anything "official" here. :) + @jin for thoughts!

**Comment by hsyed** [comment]
@Pmcneice kapt is supported and far more consistent than the plugins in Gradle which can stop working randomly between releases and or how the gradle daemon started up. It works reliably and will produce annotations in mixed mode compiles. 

See the example app and the tests.

**Comment by jin** [comment]
@davidstanke thanks for the ping! Let me sync up with the maintainers of https://github.com/bazelbuild/rules_android and see what the plans are for Kotlin Android rules.

**Comment by jin** [comment]
The rules_android and Bazel maintainers are fully invested into migrating the native Android rules out of the Bazel source tree and into their Skylark implementations, and unfortunately we don't have the free cycles to work on kt_android_library. The good news is that once we have the Android rules in Skylark, extending them would be a lot simpler than it is currently.

**Comment by hsyed** [comment]
#117 done.

**Comment by Pmcneice** [comment]
I've been following this closely - I'm excited :) Thanks for all the hard work.
