### ISSUE TITLE
Empty output generated for every target

### ISSUE THREAD

**Issue by Kernald** [bazelbuild/rules_kotlin#580]
While compiling anything with rules_kotlin (dd14b4da927b53ebba4cec59f0522dd8f08401e3), I get an output for every target in the console, even when there's no actual output (just an empty line):

```
INFO: From KotlinCompile @com_github_grpc_grpc_kotlin//stub/src/main/java/io/grpc/kotlin:context { kt: 1, java: 0, srcjars: 0 } for armeabi-v7a:
```

**Comment by cgruber** [comment]
Fixed in #586
