### ISSUE TITLE
Bazel CI: Tests failed with Bazel@HEAD due to flip of --incompatible_require_javaplugininfo_in_javacommon

### ISSUE THREAD

**Issue by coeuvre** [bazelbuild/rules_kotlin#592]
```
(04:03:38) ERROR: /var/lib/buildkite-agent/builds/bk-docker-7rs6/bazel-downstream-projects/rules_kotlin/src/test/data/jvm/kapt/BUILD:72:15: in plugins attribute of kt_jvm_library rule //src/test/data/jvm/kapt:ap_kotlin_resources_mixed: '//src/test/data/jvm/kapt:autoservice' does not have mandatory providers: 'JavaInfo'
```
Full log: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2183#ec81b610-13d5-4902-8c46-6fbf75ce9d7f
Culprit: https://github.com/bazelbuild/bazel/commit/1c062e26226d71c8e4d1fa9a72369880e867d5df
See https://github.com/bazelbuild/bazel/issues/14012

**Comment by comius** [comment]
The fix is in https://github.com/bazelbuild/rules_kotlin/pull/587
