### ISSUE TITLE
rules_kotlin broken with Bazel@HEAD CI

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/rules_kotlin#598]
Example breakage: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2214#7b100657-7658-45ec-8160-1b6bfb02f98c

```
(02:07:43) ERROR: /var/lib/buildkite-agent/builds/bk-docker-k2f7/bazel-downstream-projects/rules_kotlin/examples/android/libKtAndroid/BUILD.bazel:22:19: in plugins attribute of kt_jvm_library rule //libKtAndroid:my_kt_kt: '//libKtAndroid:serialization_plugin' does not have mandatory providers: 'JavaPluginInfo'. Since this rule was created by the macro 'kt_android_library', the error might have been caused by the macro implementation
```

I suspect this is an offshoot of https://github.com/bazelbuild/rules_kotlin/issues/592 , and that the fix therein (https://github.com/bazelbuild/rules_kotlin/pull/587) was insufficient or may contain bugs.
(This likely only arises with Bazel@HEAD due to the presence of JavaPluginInfo in Bazel@HEAD, and rules_kotlin has different behavior when JavaPluginInfo is available)

**Comment by cgruber** [comment]
Fixed in #614
