### ISSUE TITLE
Annotation Processing

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/rules_kotlin#6]
This needs some experimentation, notes:

* Need an Aspect rule so that we can render an arbitrary `java_plugin` label into an abstract set of switches or preferably an encoded payload for the worker (bazel proto format ?). 
<strike>* Unless we can cache any of the results create a single set of temp directories for all annotation processors (src, classes and stubs). (RFC: Are temp directories OK ? also used in #3).</strike> (see #10).
* If the compilers needs to be invoked twice (likely). 
  * Expand sources to include generated sources.
  * Merge classes in a separate step if needed (likely).
* RFC: look into what intellij aspects expect, if I remember correctly we need to declare the sources as a separate source jar, what about the stubs and classes ? 
* I knocked together a bit of a execution framework, a bit like the java builder. I can see the Kotlin worker becoming part of bazel core in the distant future. (RFC: Could we leverage the framework elements from the JavaBuilder, and / or potentially introduce Kotlin into the Worker ?)

**Comment by hsyed** [comment]
kapt3 doesn't respect the processors attribute (likely I am encoding it incorrectly), it will happily discover processors from the classpath though. 

[Issue]( https://youtrack.jetbrains.com/issue/KT-22764)

**Comment by hsyed** [comment]
implemented in #16 intellij support works well enough with dagger. The references are resolved against the compiled classes, an improvement would be to generate an annotations processing src jar and pass that through, happy for a PR on this.

**Comment by cgruber** [comment]
Note, we really don't want to rely on classpath discovery.  That's not a required feature of javax.annotation.processing implementations, though it happens to work in javac and kapt3 for now. But we shouldn't rely on non-spec behavior.  It's fine for now, but once jetbrains attends to your issue with kapt3 configuration, we should revert to explicitly passing the processors via java_plugin targets.

As to "compilers being invoked twice" - is that necessary?  I know javac does multiple "rounds" - I assume kapt3 does this also, with kotlinc, but I don't know that for sure.

**Comment by hsyed** [comment]
On classpath discovery: Kapt does not respect the processor list so what I have done for the time being is exclude the plugin entry entirely if it has a null or empty `processor_class` attribute. Need to wait on JB (link to issue above) to fix this.

Kotlinc does need to be invoked twice once with the kapt plugin config and once without, but this is done within the kotlin builder within the [same function](https://github.com/bazelbuild/rules_kotlin/blob/57497866f3157cb8fd1a44943ca26846fdcada1e/kotlin/workers/src/io/bazel/ruleskotlin/workers/compilers/jvm/actions/KotlinMainCompile.kt#L67-L101) so the overhead I suspect is very low.

**Comment by hsyed** [comment]
[Kotlin Youtrack issue](https://youtrack.jetbrains.com/issue/KT-22939) for annotation processor classes configuration.

**Comment by hsyed** [comment]
Fixed since 1.2.40
