### ISSUE TITLE
Are there plans to support passing through extra flags to kotlinc?

### ISSUE THREAD

**Issue by geoffliu** [bazelbuild/rules_kotlin#651]
Related to #603 , perhaps a super set of it. I'd like to pass extra compiler flags that are not currently enumerated in kt_kotlinc_options. My current use case is to configure the JS IR compiler, but the broader point is that there will always be a lag between new compiler features being made available and bazel rules catching up. Having a generic way to use these flags would be helpful. I'm happy to contribute to PRs, but I wanted to gauge interest from project owners first.

**Comment by restingbull** [comment]
No, given the rationale here: https://github.com/bazelbuild/rules_kotlin/issues/396

**Comment by restingbull** [comment]
We do accept patches to add to flags to the compiler options -- in fact it stands a as a "soft gate" for new features and lets us gauge usage and which direction to push the test matrices.
