### ISSUE TITLE
kt_jvm_library fails to sync using latest intellj plugin

### ISSUE THREAD

**Issue by cdickson-sum** [bazelbuild/rules_kotlin#674]
Using the 1.5.0 and intellij plugin releases since v2021.11.30 fails to sync with the following error:

Error:/ <pathtoproject>/workspaces/project/service/BUILD.bazel:38:15: in @intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect aspect on kt_jvm_library rule //project_services:app_lib: 

The project builds fine from the command line. It also syncs fine in intellj with the v2021.11.30 plugin. Updating the plugin to anything past this version in either Intellij 2021.2.x or 2021.3.x has the same behavior.

`kt_jvm_library(
    name = "app_lib",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    plugins = [
        "//:mn_aop_around",
        "//:no_arg_plugin",
    ],
    deps = [
        ":java_deps",
        "//:micronaut_lib",
    ],
)`

**Comment by cgruber** [comment]
Could you please provide more information about this, notably a reproduction case, or at least your configuration and the full set of errors. It's really hard to work out what's going on from this.

**Comment by cdickson-sum** [comment]
I found the solution. This turned out to be an older default java toolchain being brought into the project. I was able to fix it by adding
`http_archive(
        name = "remote_java_tools_darwin",
        sha256 = "d09141a35e2c7950f6b7ea344ebd67868146fd2d1ee2b7509cdc36a42786cca4",
        urls = [
            "https://mirror.bazel.build/bazel_java_tools/releases/java/v11.3/java_tools_darwin-v11.3.zip",
            "https://github.com/bazelbuild/java_tools/releases/download/java_v11.3/java_tools_darwin-v11.3.zip",
        ],
    )`
to my workspace to get the latest 11 toolchain. I have since been able to update to the lastest of the plugin and the rule, have them work together.
