### ISSUE TITLE
v1.5.0-beta-4 -> v1.5.0 version upgrade broke kotlin compiler plugin

### ISSUE THREAD

**Issue by oliviernotteghem** [bazelbuild/rules_kotlin#682]
Gave a try upgrading our apps to 1.5.0 and ran into the following error :

ERROR: feature/subscription/BUILD.bazel:4:15: in deps attribute of kt_jvm_library rule //feature/subscription:src_main: '//rules/thrift:open_for_testing_plugin' does not have mandatory providers: 'JavaInfo'

rules/thrift/BUILD.bazel

```
load("@io_bazel_rules_kotlin//kotlin:core.bzl", "kt_compiler_plugin")
kt_compiler_plugin(
    name = "open_for_testing_plugin",
    id = "org.jetbrains.kotlin.allopen",
    options = {
        "annotation": "com.uber.model.core.annotation.ThriftElement",
    },
    deps = [
        "@com_github_jetbrains_kotlin//:allopen-compiler-plugin",
    ],
    visibility = ["//visibility:public"],
)
```

feature/subscription/BUILD.bazel

```
kt_jvm_library(
    name = "src_main",
    plugins = ["//rules/thrift:open_for_testing_plugin"],
    visibility = ["//visibility:public"],
    .....

```

**Comment by oliviernotteghem** [comment]
@restingbull : probably related to https://github.com/bazelbuild/rules_kotlin/commit/87e95e5a689bef4d57372b1c6769e8acf5c53c30 ?

**Comment by cgruber** [comment]
This is weird, since the anvil example passes. Can you put this into a repro branch we can play with?

**Comment by cgruber** [comment]
NVM, think we found it. @restingbull thinks he has a fix.

**Comment by oliviernotteghem** [comment]
@cgruber : thanks for looking into it. Looking at the recent fixes, I think one scenario we might not support when removing JavaInfo is if dependency if both present as `deps` and `plugin`

**Comment by restingbull** [comment]
A compiler_plugin shouldn't be in kt_jvm_library.deps, it wouldn't provide anything useful.

We did have a hard check on kt_compiler_plugin.deps which I took out. Trying to repro to make sure we fixed it.

**Comment by oliviernotteghem** [comment]
Thanks for the guidance! Indeed, specifying target both as 'deps' and 'plugin' is now banned in 1.5.0, and was supported in previous version probably accidentally. Removing the target from 'deps' fixes our issues!
