### ISSUE TITLE
v1.5.0 zip file is malformed error message when trying to add dependency on rules kotlin 1.5.0

### ISSUE THREAD

**Issue by xykivo** [bazelbuild/rules_kotlin#693]
WORKSPACE file:

...
http_archive(
    name = "io_bazel_rules_kotlin",
    sha256 = "12d22a3d9cbcf00f2e2d8f0683ba87d3823cb8c7f6837568dd7e48846e023307",
    strip_prefix = "rules_kotlin-1.5.0",
    url = "https://github.com/bazelbuild/rules_kotlin/archive/v1.5.0.zip",
)

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")

kotlin_repositories()
kt_register_toolchains()
...

This is the output of running bazel build:

INFO: Repository io_bazel_rules_kotlin instantiated at:
  /Users/ds/Code/xykivo/percipio/WORKSPACE:99:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_ds/8060942439c1322d7ea154b92d378271/external/bazel_tools/tools/build_defs/repo/http.bzl:364:31: in <toplevel>
INFO: Repository 'io_bazel_rules_kotlin' used the following cache hits instead of downloading the corresponding file.
 * Hash '12d22a3d9cbcf00f2e2d8f0683ba87d3823cb8c7f6837568dd7e48846e023307' for https://github.com/bazelbuild/rules_kotlin/archive/v1.5.0.zip
If the definition of 'io_bazel_rules_kotlin' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'io_bazel_rules_kotlin':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_ds/8060942439c1322d7ea154b92d378271/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error extracting /private/var/tmp/_bazel_ds/8060942439c1322d7ea154b92d378271/external/io_bazel_rules_kotlin/temp3239179432656349520/v1.5.0.zip to /private/var/tmp/_bazel_ds/8060942439c1322d7ea154b92d378271/external/io_bazel_rules_kotlin/temp3239179432656349520: Zip file 'v1.5.0.zip' is malformed. It does not contain an end of central directory record.
ERROR: /Users/ds/Code/xykivo/percipio/WORKSPACE:99:13: fetching http_archive rule //external:io_bazel_rules_kotlin: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_ds/8060942439c1322d7ea154b92d378271/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error extracting /private/var/tmp/_bazel_ds/8060942439c1322d7ea154b92d378271/external/io_bazel_rules_kotlin/temp3239179432656349520/v1.5.0.zip to /private/var/tmp/_bazel_ds/8060942439c1322d7ea154b92d378271/external/io_bazel_rules_kotlin/temp3239179432656349520: Zip file 'v1.5.0.zip' is malformed. It does not contain an end of central directory record.
ERROR: no such package '@io_bazel_rules_kotlin//kotlin': java.io.IOException: Error extracting /private/var/tmp/_bazel_ds/8060942439c1322d7ea154b92d378271/external/io_bazel_rules_kotlin/temp3239179432656349520/v1.5.0.zip to /private/var/tmp/_bazel_ds/8060942439c1322d7ea154b92d378271/external/io_bazel_rules_kotlin/temp3239179432656349520: Zip file 'v1.5.0.zip' is malformed. It does not contain an end of central directory record.
INFO: Elapsed time: 0.564s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    Fetching ...22d7ea154b92d378271/external/io_bazel_rules_kotlin; Extracting /private/var/tmp/_bazel_ds/8060942439c1322d7ea154b92d378271/external/io_bazel_rules_kotlin/temp3239179432656349520/v1.5.0.zip

**Comment by xykivo** [comment]
Note that the following works

RULES_KOTLIN_VERSION = "legacy-1.3.0"
http_archive(
    name = "io_bazel_rules_kotlin",
    sha256 = "4fd769fb0db5d3c6240df8a9500515775101964eebdf85a3f9f0511130885fde",
    strip_prefix = "rules_kotlin-%s" % RULES_KOTLIN_VERSION,
    url = "https://github.com/bazelbuild/rules_kotlin/archive/%s.zip" % RULES_KOTLIN_VERSION,
)

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")

kotlin_repositories()
kt_register_toolchains()


It seems to me that something went wrong with any releases after 1.3.0, since I get the malformed message for all releases post 1.3.0

**Comment by restingbull** [comment]
Which version of Bazel are you using?

**Comment by xykivo** [comment]
OS: Windows, Ubuntu 20.04, MacOS (Montery) - I tried all three
Bazel version: 5.0.0

**Comment by xykivo** [comment]
Note that the output above is from MacOS, but I get similar output on Windows and Ubuntu,

**Comment by ttiurani** [comment]
@xykivo This works for me:

```starlark
RULES_KOTLIN_VERSION = "v1.5.0"
RULES_KOTLIN_SHA256 = "12d22a3d9cbcf00f2e2d8f0683ba87d3823cb8c7f6837568dd7e48846e023307"
http_archive(
    name = "io_bazel_rules_kotlin",
    url = "https://github.com/bazelbuild/rules_kotlin/releases/download/%s/rules_kotlin_release.tgz" % RULES_KOTLIN_VERSION,
    sha256 = RULES_KOTLIN_SHA256,
)

load("@io_bazel_rules_kotlin//kotlin:repositories.bzl", "kotlin_repositories")
kotlin_repositories()

load("@io_bazel_rules_kotlin//kotlin:core.bzl", "kt_register_toolchains")
kt_register_toolchains()
```

**Comment by restingbull** [comment]
Ah -- we don't upload a zip of the rules. I'm quite surprised that one is available.

Where did you get the address?

**Comment by xykivo** [comment]
Using tgz instead of zip solved the issue - my bad.
Thanks !

**Comment by ttiurani** [comment]
> Where did you get the address?

It's at the bottom of the release page, in "Assets":

https://github.com/bazelbuild/rules_kotlin/releases/tag/v1.5.0
