### ISSUE TITLE
kt_jvm_binary cannot find main entry point

### ISSUE THREAD

**Issue by xykivo** [bazelbuild/rules_kotlin#695]
When I try to run a kt_jvm_binary I get the following error:
Error: Main method not found in class com.xykivo.percipio.basics.Main, please define the main method as:
   public static void main(String[] args)

Bazel version: 5.0.0-homebrew
Rules kotlin version: legacy-1.3.0

Build file:
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_binary")

kt_jvm_binary(
    name = "ktbasics",
    srcs = glob(["src/**/*.kt"]),
    main_class = "com.xykivo.percipio.basics.Main",
)

Source file:
package helloworld

class Main {
    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            println("hello world")
            return 0
        }
    }
}

Trying to use MainKt and a standalone main function also doesn't work, e.g.
BUILD file:
load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_binary")

kt_jvm_binary(
    name = "ktbasics",
    srcs = glob(["src/**/*.kt"]),
    main_class = "MainKt"
)

Source file:
package helloworld

fun main(args: Array<String>) {
    println("hello world")
}

I get the following error:
/private/var/tmp/_bazel_ds/8060942439c1322d7ea154b92d378271/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/kotlin/basics/ktbasics: line 260: fg: no job control
/private/var/tmp/_bazel_ds/8060942439c1322d7ea154b92d378271/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/kotlin/basics/ktbasics: line 261: fg: no job control
/private/var/tmp/_bazel_ds/8060942439c1322d7ea154b92d378271/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/kotlin/basics/ktbasics: line 262: fg: no job control
Error: Could not find or load main class MainKt
Caused by: java.lang.ClassNotFoundException: MainKt

**Comment by arunkumar9t2** [comment]
Does 

```python
main_class = "helloworld.MainKt"
```

work?

**Comment by xykivo** [comment]
Yes it works !
Thanks
