### ISSUE TITLE
Issue with "jdeps automatically generated from kt_jvm_library rules" and genrule

### ISSUE THREAD

**Issue by brettwooldridge** [bazelbuild/rules_kotlin#696]
There is an issue with generating jdeps as a side-effect of ``kt_jvm_library`` as follows...

Given a ``kt_jvm_library`` target:
```
kt_jvm_library(
   name = "com-dancer-provider-collection",
    ...
)
```
And a ``genrule`` target that depends on the jar created above:
```
genrule(
   name = "com-dancer-provider-collection-hollow-gen",
   cmd_bash = "kotlin -cp $(location :com-dancer-provider-collection) dancer.provider.collection.GenerateClassesKt $(RULEDIR)"
   ...
)
```
An error is generated indicating that the target ``:com-dancer-provider-collection`` has *two outputs* and therefore ``$(locations)`` should be used instead of ``$(location)``. Those two outputs are the .jar file and the jdeps. However, using ``$(locations)`` is not possible because it generates an incorrect classpath for the ``kotlin`` invocation.

This seems undesirable.

I was able to craft an ugly workaround as follows:
```
load("//:functions.bzl", "get_compile_jar")

get_compile_jar(
    name = "collection-jar",
    lib = ":com-dancer-provider-collection",
)

genrule(
   name = "com-dancer-provider-collection-hollow-gen",
   cmd_bash = "kotlin -cp $(location :collection-jar) dancer.provider.collection.GenerateClassesKt $(RULEDIR)"
   ...
)
```
Where ``get_compile_jar()`` is defined in ``functions.bzl`` as:
```
def _compileJarImpl(ctx):
    path = ctx.attr.lib[JavaInfo].java_outputs[0].compile_jar
    return [
        DefaultInfo(files = depset([path])),
    ]

get_compile_jar = rule(
    implementation = _compileJarImpl,
    attrs = {
        "lib": attr.label(),
    },
)
```
By taking ``java_outputs[0].compile_jar`` I am able to get just the .jar file (where ``java_outputs[1]`` references the jdeps output) and set that as the singlar output of the ``get_compile_jar`` rule. This works but is ugly. I do not think that the standard ``java_library`` rule output behaves in this way, though I could be wrong.

**Comment by restingbull** [comment]
Notes:
jdeps is returned as part of the default file outputs.

https://github.com/bazelbuild/rules_kotlin/blob/master/kotlin/internal/jvm/impl.bzl#L42-L43

Decision needs to be made wether to keep them as part of the implicit outputs.

**Comment by restingbull** [comment]
Will remove the jdeps from DefaultInfo.

**Comment by restingbull** [comment]
Open Question: Where does unused dependencies get jdeps from?

**Comment by brettwooldridge** [comment]
@restingbull It looks like the ``JavaInfo`` structure contains a field explicitly for *jdeps*. So, the rule can generate a single output (``JavaInfo``), with this field populated:

https://github.com/bazelbuild/bazel/blob/01a46f05dc79db2313c6c8e174a5d6eab474aefc/src/test/java/com/google/devtools/build/lib/rules/java/JavaInfoRoundtripTest.java#L88
