### ISSUE TITLE
Switch rule naming scheme and start design docs

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/rules_kotlin#7]
For the jvm rules the prefix will switch from kotlin_ to kt_jvm_. 

I could add a macro layer for backwards compatibility but is there a point ? The intellij rules would also need to be updated.

@cgruber i am in agreement with all of the points you have raised. We should start a design doc in this repo. could you tabulate  your email in a doc here , in design ?

In terms of in source docs I think rst (as used in rules_go) is appropriate. Much better cross referencing.

Anyhow I added kotlin_import and an internal kotlin_stdlib. I’ll move the latter to kt_stdlib as its used to declare the kotlin compiler jars. kotlin_import will go away i think, if we do need to keep it arround it will probably be multi-platform, should  we shortened to kt_ ? 

Please  have  a look at my issue on ijars in bazel core. If we can classify the jar type during ijar processing it will simplify the design of the skylark logic.

**Comment by cgruber** [comment]
Sorry I've been rather out of pocket for a bit.  I'm still a bit pressed with my main project, but I'll try to get to this next week.

**Comment by cgruber** [comment]
Do you want to just add me to this project and assign this to me, since I have an action item?

**Comment by hsyed** [comment]
@davidstanke could you add christian to the project.

**Comment by hsyed** [comment]
#89 will lead to a design document for making a start on the challenging bits. The jvm rules don't need any "design work".
