### ISSUE TITLE
Add support for new mode for generating default interface 

### ISSUE THREAD

**Issue by oliviernotteghem** [bazelbuild/rules_kotlin#714]
See : https://blog.jetbrains.com/kotlin/2020/07/kotlin-1-4-m3-generating-default-methods-in-interfaces/ 

We should be able to pass 'all' (and all-compatibility) for jvm-default option when target >= 1.8

This will enable removing #JvmDefault which is getting deprecated

**Comment by Bencodes** [comment]
@oliviernotteghem rules_kotlin already has support for a subset of the JVM default options. I opened up the PR to add the rest. https://github.com/bazelbuild/rules_kotlin/pull/715

**Comment by oliviernotteghem** [comment]
Thanks Ben!
