### ISSUE TITLE
Module names are not being initialized to sane defaults.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/rules_kotlin#8]
kt_jvm_library is not defining the module name. We could iniialize it from the label name by default, as well as providing an override attribute.

**Comment by hsyed** [comment]
@cgruber I've just started initialising the module names to the rule name. But we probably need to be able to override this explicitly. Does a top level `module_name` attribute make sense ?

**Comment by cgruber** [comment]
module_name in kt_*_lib does seem like a reasonable configuration, though I agree, the default is probably derivable from the bazel context.

Though I'm not sure the rule name is the right one, or some construct containing the bazel package_rule. some_package_path_rulename seems like it's a more solid namespace, but honestly, I am not sure what the ideal is, as I haven't done enough bazel stuff to know if how people arrange their packages would typically result in a reasonable default. (in google we do that for blaze but that's becasue we have a pattern internally of following the java package structure. 

At any rate, whatever default wins in the long-run, having an overridable module_name seems quite reasonable.

**Comment by hsyed** [comment]
@cgruber added both suggestions in #25, just wondering what bazel is going to do for jdk9 modules. Would be nice to use the same generation strategy.

**Comment by cgruber** [comment]
Gonna have to ask the bazel team re: jdk9.  I am not looped in to that decision making process.

**Comment by hsyed** [comment]
Module names are being initialized. The JDK9 issue should be tracked seperately when the time is right.
