### ISSUE TITLE
Expose KT rules to be used in stardoc generation of custom rules

### ISSUE THREAD

**Issue by tharakadesilva** [bazelbuild/rules_kotlin#805]
I am writing my own set of rules on top of `rules_kotlin`, but my stardoc generation is failing due to the "limited visibility" in `rules_kotlin`.

There is an open issue https://github.com/bazelbuild/stardoc/issues/93 to add a better fix for this.

Till then, would it be possible to expose a `bzl_library` similar to https://github.com/bazelbuild/rules_jvm_external/pull/527?

**Comment by restingbull** [comment]
Duplicate of 572
