### ISSUE TITLE
Bazel@HEAD CI failing for rules_kotlin

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/rules_kotlin#823]
Related to breaking Bazel change https://github.com/bazelbuild/continuous-integration/issues/1404

Likely because of this repository's dependency on an old version of rules_nodejs

Example failure: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2590#0182aecd-b22e-4451-9ec9-4acabee5f50b

**Comment by restingbull** [comment]
Will bump version and see if that fixes.

**Comment by restingbull** [comment]
No longer failing: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2657
