### ISSUE TITLE
Serialization plugin doesn't work with language version 1.6

### ISSUE THREAD

**Issue by hanneskaeufler** [bazelbuild/rules_kotlin#863]
When being pinned to language version 1.6, it seems as if there is some version conflict somewhere which breaks the serialization. I was able to (somewhat) reproduce this by the following commit in the examples here:

https://github.com/hanneskaeufler/rules_kotlin/commit/4521d3d9361fae41440b907aa6d00f64b47cb387

I am on macOS and seeing

```
~/Code/rules_kotlin/examples/plugin (master) bazel test //src/serialization/... --test_output=all
DEBUG: /private/var/tmp/_bazel_hanneskaeufler/41ba52e1752ec46c5b89935dc26f43d2/external/release_archive/repository.bzl:45:14: build Fr  4 Nov 2022 21:22:24 CET
INFO: Analyzed 4 targets (64 packages loaded, 1407 targets configured).
INFO: Found 3 targets and 1 test target...
ERROR: /Users/hanneskaeufler/Code/rules_kotlin/examples/plugin/src/serialization/BUILD:26:15: KotlinCompile //src/serialization:data { kt: 1, java: 0, srcjars: 0 } for darwin_arm64 failed: (Exit 1): build failed: error executing command bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/io_bazel_rules_kotlin/src/main/kotlin/build '--flagfile=bazel-out/darwin_arm64-fastbuild/bin/src/serialization/data-kt.jar-0.params'
exception: java.lang.AbstractMethodError: Receiver class io.bazel.kotlin.plugin.jdeps.JdepsGenCommandLineProcessor does not define or inherit an implementation of the resolved method 'abstract void appendList(org.jetbrains.kotlin.config.CompilerConfiguration, org.jetbrains.kotlin.config.CompilerConfigurationKey, java.lang.Object)' of interface org.jetbrains.kotlin.compiler.plugin.CommandLineProcessor.
	at io.bazel.kotlin.plugin.jdeps.JdepsGenCommandLineProcessor.processOption(JdepsGenCommandLineProcessor.kt:47)
	at org.jetbrains.kotlin.cli.jvm.plugins.PluginCliParserKt.processCompilerPluginsOptions(PluginCliParser.kt:125)
	at org.jetbrains.kotlin.cli.jvm.plugins.PluginCliParser.processPluginOptions(PluginCliParser.kt:83)
	at org.jetbrains.kotlin.cli.jvm.plugins.PluginCliParser.loadPlugins(PluginCliParser.kt:72)
	at org.jetbrains.kotlin.cli.jvm.plugins.PluginCliParser.loadPluginsSafe(PluginCliParser.kt:44)
	at org.jetbrains.kotlin.cli.common.CLICompiler.loadPlugins(CLICompiler.kt:187)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:71)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:54)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:91)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:43)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
```

with those versions. To be fair, on windows I was seeing something slightly different, so I'm not even sure I am reproducing the correct thing. Nevertheless, this also seems like an unintended breakage here.
Excuse me if I open the issue on the wrong project, feel free to direct me towards the likely point of failure.
Any help appreciated, thanks!

**Comment by hanneskaeufler** [comment]
I don't really understand how they are being used, but there seems to be

https://github.com/bazelbuild/rules_kotlin/blob/master/src/main/starlark/core/repositories/setup.bzl#L45

whose version we are unable to change from the outside.

There is also https://github.com/bazelbuild/rules_kotlin/blob/master/examples/plugin/src/serialization/BUILD#L10 which doesn't fix the error no matter which version I pick.

**Comment by hanneskaeufler** [comment]
Output from CI run in repro PR #864 : https://buildkite.com/bazel/rules-kotlin-kotlin/builds/2883#01844454-a7e2-4483-a2e9-cbfb28d7d11c

**Comment by restingbull** [comment]
Should be fixed by https://github.com/bazelbuild/rules_kotlin/pull/859

**Comment by restingbull** [comment]
lmk if it shows up again -- the plugin api seems to be in flux.

**Comment by hanneskaeufler** [comment]
Thanks for the super quick response, will check it out on monday  <3

**Comment by hanneskaeufler** [comment]
I guess since I'm now running into https://github.com/Kotlin/kotlinx.serialization/issues/2090 I would consider this issue here fixed :) Thanks again
