### ISSUE TITLE
x_optin attribute is not available for kt_javac_options rule definition despite documentation claiming that it is

### ISSUE THREAD

**Issue by JemarJones** [bazelbuild/rules_kotlin#871]
Here is the documentation claiming the attribute is available: https://github.com/bazelbuild/rules_kotlin/blob/master/README.md#kotlin-and-java-compiler-flags
![image](https://user-images.githubusercontent.com/6874590/200959667-b66cc63c-9e45-4bef-a6d1-b4a437508665.png)

Here is where the attributes for this rule are defined: https://github.com/bazelbuild/rules_kotlin/blob/master/src/rkt_1_7/starlark/jvm/opts.bzl#L4. The `x_optin` option is not there.

Attempting to use the attribute for this rule yeilds this error `no such attribute 'x_optin' in 'kt_javac_options' rule`.

As i read more, I think i'm probably misunderstanding what `x_optin` is for (seems like its for enabling specific experimental features in the Kotlin language?), but this documentation doesn't help.

PS: What i'm actually trying to find is a way to pass an arbitrary compiler flag to javac, is this supported? Or am i SOL if the flag i need to pass isn't one of the explicitly defined attributes?

**Comment by restingbull** [comment]
Ah, bad documentation. 

`x_optin` is a `kt_kotlinc_option`, not a `kt_javac_option`.

> PS: What i'm actually trying to find is a way to pass an arbitrary compiler flag to javac, is this supported? Or am i SOL if the flag i need to pass isn't one of the explicitly defined attributes?
See https://github.com/bazelbuild/rules_kotlin/issues/396
