### ISSUE TITLE
`experimental_strict_kotlin_deps` is not always able to tell which dependency is missing

### ISSUE THREAD

**Issue by erlendvollset** [bazelbuild/rules_kotlin#874]
As you can see in the screen shot, these often appear as `null`, making it impossible to find out which target we need to include.

![Screen Shot 2022-11-15 at 15 48 27](https://user-images.githubusercontent.com/5850532/201949496-b596db0f-a407-4c30-aa5b-8ccfd30a26d5.png)

**Comment by lukaciko** [comment]
See #705.

**Comment by erlendvollset** [comment]
Closing in favor of #705. The suggested fixes there worked for me 🥳
