### ISSUE TITLE
Configure CI so that host_javabase  1.8 and 1.9 are covered.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/rules_kotlin#88]
@buchgr could you update the yml file if you get a chance. I don't know the format.  (Could do with a link to documentation in the yml file if there is any, I had a quick look arround)

We could just run `1.8` on ubuntu `14.*` and 1.9 on `16.*`.

**Comment by buchgr** [comment]
@hsyed we don't have machines with java 9 installed (yet). We'll only move once Bazel's java rules can build with a JDK9 java base.

**Comment by hsyed** [comment]
@buchgr [comment](https://github.com/bazelbuild/bazel/issues/5483#issuecomment-402239814) the embedded jdk9 would work.

**Comment by buchgr** [comment]
@hsyed yep that should work, but it will only be on Java 9 once Bazel 0.16.0 is released.

**Comment by cgruber** [comment]
Obsolete.
