### ISSUE TITLE
invalid user-provided repo name ''

### ISSUE THREAD

**Issue by Clement-Jean** [bazelbuild/rules_kotlin#883]
I'm trying to use this rule and I simply want to use the default compiler and toolchains. So I added this in my WORKSPACE:

```
rules_kotlin_version = "1.6.0"
rules_kotlin_sha = "a57591404423a52bd6b18ebba7979e8cd2243534736c5c94d35c89718ea38f94"
http_archive(
    name = "io_bazel_rules_kotlin",
    urls = ["https://github.com/bazelbuild/rules_kotlin/releases/download/v%s/rules_kotlin_release.tgz" % rules_kotlin_version],
    sha256 = rules_kotlin_sha,
)

load("@io_bazel_rules_kotlin//kotlin:repositories.bzl", "kotlin_repositories")
kotlin_repositories()

load("@io_bazel_rules_kotlin//kotlin:core.bzl", "kt_register_toolchains")
kt_register_toolchains()
```

but once I build, I have the following error:

```
ERROR: Traceback (most recent call last):
	File "/Users/clement/Git/protobuf/WORKSPACE.bzlmod", line 13, column 20, in <toplevel>
		kotlin_repositories()
	File "/private/var/tmp/_bazel_clement/5892ceef4629d9b2aad305f593ba52a0/external/io_bazel_rules_kotlin/src/main/starlark/core/repositories/initialize.bzl", line 96, column 21, in kotlin_repositories
		rules_repository(
Error in repository_rule: invalid user-provided repo name '': valid names may contain only A-Z, a-z, 0-9, '-', '_', '.', and must start with a letter
```

This is seems weird to me because I check [intialize.bzl](https://github.com/bazelbuild/rules_kotlin/blob/16445ede99d4056e4a9c464e2b8133b2d8d0fa4a/src/main/starlark/core/repositories/initialize.release.bzl#L108) where it uses `rules_repository` and I can't figure out where the repo name could be wrong.

## Edit

This is in the context of bzlmod. Apprently bzlmod has stricter repository name validation ([ref](https://github.com/bazelbuild/bazel-central-registry/issues/320#issuecomment-1350754084))

**Comment by restingbull** [comment]
[bzlmod](https://github.com/bazelbuild/rules_kotlin/pull/878) support is still in progress. Will ping back when it's working.

**Comment by vadym-sedna** [comment]
any progress on this?

**Comment by gregorycollins** [comment]
@vadym-sedna I think the reason this may be happening is that bazel 6.0.0 was just released, and `bazelisk` auto-updates

**Comment by jmthvt** [comment]
It looks like this is not correctly skipped with bazel 6.0 https://github.com/bazelbuild/rules_kotlin/blob/e5c457c508f21f43f1686ce9be928d2e2a4fd6f8/src/main/starlark/core/repositories/initialize.release.bzl#L99

**Comment by restingbull** [comment]
That is very odd -- python has always considered an empty string to be false.

**Comment by restingbull** [comment]
> The current code should work but we clearly see it passes the condition 🤔 am I missing something?
Could be a regression -- bzlmod changed a lot of weird things in the repository runtime. Let me try to  repro.

Till then, this seems like a reasonable work around.

**Comment by restingbull** [comment]
No longer an issue in 1.8
