### ISSUE TITLE
Design document for a `kt_library` rule.

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/rules_kotlin#89]
I think before tackling JS we need a `kt_library` and have it fully working with the JVM rules. 

Considering just the JVM aspect. A `kt_library` at the very least is a list of src files and it should be "somehow" be used in `kt_jvm_library`. Extending this to multiplatform a `kt_library` could be multiplatform. In which case to create a `kt_jvm_library` it would need srcs containing the JVM `actual` instances. 

```py
kt_library(
  name = "foo_api",
  srcs = glob(["api/*.kt"])
)

kt_jvm_library(
  name = "foo_jvm",
  expected_by = [ ":api" ] # should this be list or single ? 
  srcs = [ "jvm/*.kt" ]
)
```

Some questions: 

1. Is a `kt_library` always multiplatform -- can it be used just to group sources together --i.e., should it also be allowed in the srcs list of `kt_jvm_library`, `kt_js_library` ?.
2. If a multiplatform library isn't always multiplatform do we need to explicetly mark it multiplatform or is this knowledge only required when compiling it --i.e., by virtue of being featured in the `expected_by` attribute ?
3. What do the providers look like ?

**Comment by thewoolleyman** [comment]
Hi @hsyed ,

Just checking in.  I made an attempt to just hack this to work by creating a `kt_js_library` rule, and just define a parallel execution/provider path for js files.

However, with my limited knowledge of Bazel I got stuck on what to do with the `KotlinBuilder` class and toolchain, which is currently JVM-specific.

Would love to see this working, but I don't know enough about Bazel yet to proceed any further without significant guidance/direction.

So, putting this on the back burner for now and going back to Gradle to build my kotlin/js 😔

Thanks,
-- Chad

**Comment by thewoolleyman** [comment]
@hsyed 

One main thing that I realized is that in the JS ecosystem, there has to be some core concepts of managing dependencies via npm/yarn, and output bundles.

Other rules libraries implement this in various ways, for example https://github.com/bazelbuild/rules_nodejs or https://github.com/bazelbuild/rules_typescript.

Some of these also implement other features we may or may not want, e.g. building for dev mode, and running local servers (e.g. express).

My main question is: for the core stuff, dependencies and bundles, would we need to reimplement a lot of it, or would it be possible to "compose" or reuse with some of these other sets of rules like the nodejs ones.

If you want make some time to discuss this and give me more context on some of the ideas you outlined and more direction on what to hack on, I'd be happy to.  My contact info is on my profile, and I'll include my email here.

Thanks!
-- Chad
thewoolleyman@gmail.com

**Comment by alexeagle** [comment]
See my last comment in #114 - basically we need a right-shaped JS provider that TypeScript and Kotlin rules both output, then you should have no other work to fit into the JS runtime ecosystem.

**Comment by cgruber** [comment]
this is obsolete at this point. We generally need to update overview documentation.
