### ISSUE TITLE
Unable to use Kotlin 1.8.0

### ISSUE THREAD

**Issue by brettwooldridge** [bazelbuild/rules_kotlin#908]
I am using rules_kotlin v1.7.1. I am trying to use the latest version of Kotlin, 1.8.0. However, when I do, I get various errors associated with various (supported) options to ``kt_kotlinc_options``.

In WORKSPACE:
```
kotlin_repositories(
    compiler_release = kotlinc_version(
        release = "1.8.0",
        sha256 = "0bb9419fac9832a56a3a19cad282f8f2d6f1237d2d467dc8dfe9bd4a2a43c42e",
    ),
)
```

In BUILD.bazel:
```
kt_kotlinc_options(
    name = "kt_kotlinc_options",
    x_lambdas = "indy",
    x_optin = ["kotlin.Experimental"],
    x_sam_conversions = "class",
)

define_kt_toolchain(
    name = "kotlin_toolchain",
    api_version = "1.7",
    experimental_use_abi_jars = True,
    jvm_target = "17",
    kotlinc_options = "//:kt_kotlinc_options",
    language_version = "1.7",
)
```

Errors:
```
ERROR: /Users/brettw/Documents/lvi/netld/BUILD.bazel:3:19: //:kt_kotlinc_options: no such attribute 'x_lambdas' in 'kt_kotlinc_options' rule
ERROR: /Users/brettw/Documents/lvi/netld/BUILD.bazel:3:19: //:kt_kotlinc_options: no such attribute 'x_optin' in 'kt_kotlinc_options' rule
ERROR: /Users/brettw/Documents/lvi/netld/BUILD.bazel:3:19: //:kt_kotlinc_options: no such attribute 'x_sam_conversions' in 'kt_kotlinc_options' rule
```

However, when I change the ``kotlin_repositories`` entry back to ``1.7.21`` with sha256 ``8412b31b808755f0c0d336dbb8c8443fa239bf32ddb3cdb81b305b25f0ad279e``, everything works as it did before (no errors).

I can't seem to figure it out. Any idea what is wrong?

**Comment by Bencodes** [comment]
There's a PR up with WIP support for Kotlin 1.8 but it's not done yet. https://github.com/bazelbuild/rules_kotlin/pull/910

**Comment by brettwooldridge** [comment]
@Bencodes Anything I can do to help? Something you need someone to look into?

**Comment by Bencodes** [comment]
Kotlin 1.8 support was just merged into master. We'll cut a new rolling release so that everyone can get testing.

**Comment by brettwooldridge** [comment]
Awesome, thanks!
