### ISSUE TITLE
What is the default toolchain called?

### ISSUE THREAD

**Issue by aryeh-looker** [bazelbuild/rules_kotlin#934]

**Comment by aryeh-looker** [comment]
This suggests to me that the default toolchain is called... unoriginally enough, `default_toolchain`, but this surprises me as I would image it would lead to name conflicts.

https://github.com/bazelbuild/rules_kotlin/blob/master/kotlin/internal/toolchains.bzl#L381

Not precisely clear how to use in a genrule...

**Comment by aryeh-looker** [comment]
Based on this, I think it's one of these -- though the name internal suggests it ought not be used

```
 % bazel cquery 'deps(//src/main/java/energy/tapestry/experimental/modelview/cimschema/typescriptclient:generate_typescript_lib)' | grep tool | grep kotlin
INFO: Invocation ID: 12898412-0049-4885-8142-939d2ef3efb6
Loading: 
Loading: 0 packages loaded
Analyzing: target //src/main/java/energy/tapestry/experimental/modelview/cimschema/typescriptclient:generate_typescript_lib (0 packages loaded, 0 targets configured)
INFO: Analyzed target //src/main/java/energy/tapestry/experimental/modelview/cimschema/typescriptclient:generate_typescript_lib (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
@io_bazel_rules_kotlin//kotlin/internal:kt_toolchain_type (0cea61a)
@io_bazel_rules_kotlin//kotlin/internal:default_toolchain_impl (0cea61a)
INFO: Elapsed time: 0.714s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
```

**Comment by restingbull** [comment]
If you look at https://github.com/bazelbuild/rules_kotlin/blob/master/kotlin/internal/toolchains.bzl#L333-L334, you'll see that macro can only be called from one package.

The default toolchain is `@io_bazel_rules_kotlin//kotlin/internal:default_toolchain`. If you run `--toolchain_resolution_debug=@io_bazel_rules_kotlin//kotlin/.*` you'll see it selected.

**Comment by aryeh-looker** [comment]
Just to double-check; when you say "[it] can only be called from one package", you are saying that it not meant for clients to use; is that correct to say?

When I do try to use `@io_bazel_rules_kotlin//kotlin/internal:default_toolchain`, I get this error, and not the message produced by `fail("kt_configure_toolchains must be called in kotlin/internal not %s" % native.package_name())`:

```
ERROR: /path/to/BUILD.bazel:36:16: in toolchains attribute of genrule rule //path/to:genrule: '@io_bazel_rules_kotlin//kotlin/internal:default_toolchain' does not have mandatory providers: 'TemplateVariableInfo'
```

**Comment by aryeh-looker** [comment]
If it is not intended to be used by clients of the build rules, I wonder if:
* it might be worth documenting that to use the kotlin toolchain directly, creating a toolchain is _required_
* it might be worth contemplating whether there could be a way to access a default toolchain (not necessarily this one)

If I understand correctly, introducing a toolchain means that I need to specify a version of kotlin.

If that assumption is correct, having a default toolchain could help with these issues:
* needing to answer the question "which version of kotlin have I been building against?" -- which is good to know, but is a thing -- to help decide which version to pin
* I have to coordinate with my team to decide whether that version is the one we want to be using, as it will, going forwards, be hard-coded in  `WORKSPACE`
* I need to make sure to manage the kotlin version in `WORKSPACE` as future releases of kotlin are released instead of merely using the default version furnished with each release of `bazelbuild/rules_kotlin`

^ in general all the above are reasonable to ask a client to do, but can sometimes be nice to kick down the road

**Comment by aryeh-looker** [comment]
Unfortunately I am getting a similar error when creating a toolchain per the documentation:

```
load("@io_bazel_rules_kotlin//kotlin:core.bzl", "define_kt_toolchain", "kt_javac_options", "kt_kotlinc_options")

kt_kotlinc_options(
    name = "kt_kotlinc_options",
    warn = "report",
)

kt_javac_options(
    name = "kt_javac_options",
    warn = "report",
    x_ep_disable_all_checks = False,
)

define_kt_toolchain(
    name = "kotlin_toolchain",
    javac_options = ":kt_javac_options",
    kotlinc_options = ":kt_kotlinc_options",
)

genrule(
  ...
  toolchains = [":kotlin_toolchain"],
)
```

I have had some trouble creating a minimal repro, but adding/removing this toolchain introduces/removes the same error as above, respectively:

```
Just to double-check; when you say "[it] can only be called from one package", you are saying that it not meant for clients to use; is that correct to say?

When I do try to use @io_bazel_rules_kotlin//kotlin/internal:default_toolchain, I get this error, and not the message produced by fail("kt_configure_toolchains must be called in kotlin/internal not %s" % native.package_name()):

ERROR: /path/to/BUILD.bazel:36:16: in toolchains attribute of genrule rule //path/to:genrule: '@io_bazel_rules_kotlin//kotlin/internal:default_toolchain' does not have mandatory providers: 'TemplateVariableInfo'
```

**Comment by aryeh-looker** [comment]
>I have had some trouble creating a minimal repro

i.e. this works fine. In both instances, I am using the latest stable release, 1.7.1. This minimal repro in a fresh bazel project appears to work fine:

```
# BUILD.bazel
load("@io_bazel_rules_kotlin//kotlin:core.bzl", "define_kt_toolchain", "kt_javac_options", "kt_kotlinc_options")

kt_kotlinc_options(
    name = "kt_kotlinc_options",
    warn = "report",
)

kt_javac_options(
    name = "kt_javac_options",
    warn = "report",
    x_ep_disable_all_checks = False,
)

define_kt_toolchain(
    name = "kotlin_toolchain",
    javac_options = ":kt_javac_options",
    kotlinc_options = ":kt_kotlinc_options",
)

genrule(
  name = "gen",
  cmd = "touch $@",
  outs = ["foo"]
)
```

```
# WORKSPACE
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

rules_kotlin_version = "1.7.1"
rules_kotlin_sha = "fd92a98bd8a8f0e1cdcb490b93f5acef1f1727ed992571232d33de42395ca9b3"
http_archive(
    name = "io_bazel_rules_kotlin",
    urls = ["https://github.com/bazelbuild/rules_kotlin/releases/download/v%s/rules_kotlin_release.tgz" % rules_kotlin_version],
    sha256 = rules_kotlin_sha,
)

load("@io_bazel_rules_kotlin//kotlin:repositories.bzl", "kotlin_repositories")
kotlin_repositories() # if you want the default. Otherwise see custom kotlinc distribution below

load("@io_bazel_rules_kotlin//kotlin:core.bzl", "kt_register_toolchains")
kt_register_toolchains() # to use the default toolchain, otherwise see toolchains below
```

**Comment by aryeh-looker** [comment]
As a workaround, I can use the pattern in https://github.com/bazelbuild/rules_kotlin/blob/04561a5b02914266e8aa7ad7661900ebd4171300/examples/dagger/BUILD#L83.

It's arguable that _the way things are implemented_ are actually for the best, as they involve using the whole path for compilation in bazel set out by these rules, as opposed to compiling with `kotlinc`, for example, in a `genrule`.

**Comment by aryeh-looker** [comment]
Related (deleted some comments here and replaced with this ticket): https://github.com/bazelbuild/rules_kotlin/issues/935
