### ISSUE TITLE
Using toolchain in genrule fails

### ISSUE THREAD

**Issue by aryeh-looker** [bazelbuild/rules_kotlin#935]
It's arguable that this is _designed as intended_ or at least that using the kt toolchain in a `genrule` would be a feature request as there is a decent approach in this example code, which involves creating a `srcjar` and compiling it in bazel using the `kt_jvm_library` rule (I was so stoked to see bazel allows `srcjar`s to be used in `srcs`).

https://github.com/bazelbuild/rules_kotlin/blob/04561a5b02914266e8aa7ad7661900ebd4171300/examples/dagger/BUILD#L83https://github.com/bazelbuild/rules_kotlin/blob/04561a5b02914266e8aa7ad7661900ebd4171300/examples/dagger/BUILD#L83.

It could potentially be helpful for newcomers to document the approach taken in `examples/` and the decision behind it (e.g. perhaps a section in the main `README` for compiling codegen'd sources), if the core implementors feel that this approach is strictly superior and if `TemplateVariableInfo` will never be implemented on a kt toolchain.

----

Error:

```
ERROR: /path/to/BUILD.bazel:36:16: in toolchains attribute of genrule rule //path/to:genrule: '@io_bazel_rules_kotlin//kotlin/internal:default_toolchain' does not have mandatory providers: 'TemplateVariableInfo'
```

Minimal repro:

```
# BUILD.bazel
load("@io_bazel_rules_kotlin//kotlin:core.bzl", "define_kt_toolchain")

define_kt_toolchain(
    name = "kotlin_toolchain",
)

genrule(
  name = "gen",
  cmd = "touch $@",
  outs = ["foo"],
  toolchains = [":kotlin_toolchain"]
)
```

```
# WORKSPACE
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

rules_kotlin_version = "1.7.1"
rules_kotlin_sha = "fd92a98bd8a8f0e1cdcb490b93f5acef1f1727ed992571232d33de42395ca9b3"
http_archive(
    name = "io_bazel_rules_kotlin",
    urls = ["https://github.com/bazelbuild/rules_kotlin/releases/download/v%s/rules_kotlin_release.tgz" % rules_kotlin_version],
    sha256 = rules_kotlin_sha,
)

load("@io_bazel_rules_kotlin//kotlin:repositories.bzl", "kotlin_repositories")
kotlin_repositories() # if you want the default. Otherwise see custom kotlinc distribution below

load("@io_bazel_rules_kotlin//kotlin:core.bzl", "kt_register_toolchains")
kt_register_toolchains() # to use the default toolchain, otherwise see toolchains below
```

**Comment by restingbull** [comment]
Please review the Bazel toolchain documentation: https://bazel.build/extending/toolchains

There is no support for consuming toolchains in genrules.

I would suggest writing a proper rule rule and consuming the toolchain, or opening a feature request on bazel to have toolchain access supported in genrules.

Closing as out of scope for `rules_kotlin`.
