### ISSUE TITLE
kotlin-compiler packages not found by IntelliJ

### ISSUE THREAD

**Issue by thewoolleyman** [bazelbuild/rules_kotlin#96]
When I open the `rules_kotlin` repo itself, and go to a file which uses `kotlin-compiler` classes,
such as `kotlin/builder/src/io/bazel/kotlin/compiler/BazelK2JVMCompiler.kt`, IntelliJ fails to
resolve the import paths (see attached screenshot).

I'd like these to work, because it will help me find my way around and learn the APIs faster
when hacking on this project (to add kotlin-js support, as we discussed elsewhere).

I've played with this some, and I see the reference to the compiler as a dependency
in places like [this](https://github.com/bazelbuild/rules_kotlin/blob/master/kotlin/builder/BUILD#L19).

I think the solution is to make it automatically included as a dependency in the generated `.project/.blaze/modules/.workspace.iml` module.  However, I'm unsure of the proper way to go
about that.

Happy to hack on it some more, but I'd need pointers on how to proceed.

Thanks,
-- Chad

<img width="999" alt="screen shot 2018-07-11 at 9 25 21 pm" src="https://user-images.githubusercontent.com/158/42611181-1e8b6962-8552-11e8-8392-b24337823d0a.png">

**Comment by thewoolleyman** [comment]
FYI, as a temporary workaround, adding `"@com_github_jetbrains_kotlin//:compiler"` to
`COMMON_DEPS` in `kotlin/builder/BUILD` lets IntelliJ find them, but that's obviously not
a permanent solution.

**Comment by hsyed** [comment]
Just to check, is the project synced up ? Top right corner, red icon with yellow dot in it.

 I sm pushing a refactor to the sources and how they are built  in a few hours.

**Comment by hsyed** [comment]
@thewoolleyman I've just committed some changes. It should work much more reliably now.

**Comment by hsyed** [comment]
Previous fix still had some problems. This should work.

**Comment by hsyed** [comment]
closing this as the problem no longer exists as far as I can tell.
