### ISSUE TITLE
rules_kotlin (Stardoc api documentation) is failing in Downstream CI

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_kotlin#988]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3160#01894849-5ad0-466a-9ceb-0bc3844877df

Platform : Ubuntu

Logs: 
```
ERROR: no such package 'docs': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
```

Steps : 
```
git clone -v https://github.com/bazelbuild/rules_kotlin.git
git reset b67dd8dfe4a7394001c784e88d022f3ffb490e29 --hard
export USE_BAZEL_VERSION=26926ee068ce7c18ec9a8afee49e078fa7ab6a1c
bazel test --sandbox_writable_path=/var/lib/buildkite-agent/.cache/bazelisk -- //docs:are_docs_up_to_date_test
```

CC Greenteam @SalmaSamy

**Comment by restingbull** [comment]
I hate to be the one that says "Works on my machine", but well, it does. And on [build kite as well](https://buildkite.com/bazel/rules-kotlin-kotlin/builds/3416#01894c95-a122-4c51-b485-310cb6076973)

Please re-open with a failing repro case.
